### ISSUE TITLE
more aliasing tests for cycpp

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1017]
The aliasing functionality was added in #1016 along with a few (overly) simple tests for some of the code generator filters.  Tests for the rest of the generator filters should be added.  Also, they tests could be made less simple/better.  Also, a test should probably be added for pass 2 where alias entries are added to the vars dict.

**Comment by gidden** [comment]
@rwcarlsen, can you give an update on this issue?

**Comment by rwcarlsen** [comment]
Some of the new recursion related work introduced some alias related tests.  I think we can close this for now.
