### ISSUE TITLE
sharing short-supply resources

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1027]
It would be nice if there was a mechanism to "spread" limited resources across multiple requesters.  An example:

* 3 reactors
* 1 fuel fab

The fuel fab only has 3 batches to offer.  The reactors are each looking to get 1 new batch immediately (that they need), and also to acquire 2 reserve batches.  So they each request 3 new batches.  But they only really need 1 batch for sure.  So they might set a higher preference on the first batch.  But suppose they all happen to set the higher preference on the same batch from the fab.  So when the resource exchange resolution occurs, effectively, 1 random reactor will get the first batch - since the same preference was set on it from all reactors.  And since all reactors had the same lower preferences for the extra batches as well, it is not unlikely that the reactor that got the first batch will also be matched with the 2 reserve batches leaving the other two reactors high and dry.

One possible way to deal with this sort of problem is to break ties in preferences by dynamically reordering tie breaks as you match one exchange/transfer at a time.  As soon as we give a batch to reactor A, then he immediately gets a reduced priority for ties on remaining batches.

How easy would something like this be to implement @gidden?

**Comment by gidden** [comment]
moved to 1.4

**Comment by rwcarlsen** [comment]
I'm closing this as it seems to be more appropriately implemented in cycamore.  Reactors can adjust preferences for each batch requested according to how important that batch is to them.  I'll likely be creating issues/mods to cycamore in the near future as this is all related to my dissertation a bit.
