### ISSUE TITLE
add rng to context

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1030]
the rng must not be seedable by agents.  Not only the seed, but the internal state of the rng must be storable and loadable (for restart).  A hack would be to remember the seed and how many times the rng had been called.  Restart would then reseed, and discard the prev # entries.

**Comment by gidden** [comment]
@rwcarlsen, can you give an update on this issue?

**Comment by rwcarlsen** [comment]
This will be much easier and will probably need to wait until c++11 support
is implemented. Move to 1.4.

**Comment by gidden** [comment]
to 1.4

**Comment by nuclearkatie** [comment]
Closed by #1599

**Comment by gonuke** [comment]
@nuclearkatie - I'm OK closing this, but reviewing it made we wonder about the question of whether the RNG info is comprehensively stored in the DB for restart.  If not (or if we don't know) maybe a new issue should be generated for that.
