### ISSUE TITLE
Add simple buy/sell policies to toolkit

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1033]
They currently live here: https://github.com/cyclus/kitlus.  I've been working on some updates to generalize them (https://github.com/rwcarlsen/kitlus/tree/general) for a wider range of use cases.  They will hopefully be featurefull enough to replace nearly all DRE-related code in cycamore with no more than a handful of lines.

**Comment by gidden** [comment]
now blocked on #1127

**Comment by gidden** [comment]
done
