### ISSUE TITLE
put gtest in cyclus-specific location

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1035]
currently, we install our gtest header and lib files into `[prefix]/include` and `[prefix]/lib` directly.  These install locations collide with distributions' gtest packages :(   We should either use distribution gtest dependency or move our gtest into cyclus subdirs.

**Comment by gidden** [comment]
@rwcarlsen, can you give an update on this issue?

**Comment by rwcarlsen** [comment]
no progress yet.

**Comment by gidden** [comment]
to 1.4
