### ISSUE TITLE
decay is completely dysfunctional

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1049]
Not sure when it happened.  But the decayer computes `-NaN` as the new decayed quantity of every nuclide in every composition I've tried.  I think we (and that doesn't mean everybody wait till robert does it :) should at least take a look to see if we can find the issue before we release 1.2.  No baby for us yet, but almost for sure before the end of the week - so probability is very low for me to have time for this.  I think we should add an exception throw to the material decay method for 1.2 if we don't have time to address this.  Because as it currently works, all compositions disappear and the output data are extremely wrong when decay is used.

I'm pretty sure the problem is inside the Decayer class.  I know the problem is not in the Composition class.  And I'm pretty sure we haven't made any nontrivial changes to UniformTaylor and LMatrix for a very long time (ever?).  Maybe when we switched to using pyne data, something got mangled a bit in how we populate the parent/daughters data in Decayer?

**Comment by gidden** [comment]
@rwcarlsen/@scopatz, can you give an update on this issue?

**Comment by rwcarlsen** [comment]
fixed.
