### ISSUE TITLE
update time-related constants in Material and Composition classes

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1058]
Material::Decay and decay-related code in Composition class both do month-related calcs.  These will need to be updated when the CEP 23 implementation goes in.

**Comment by gidden** [comment]
@rwcarlsen, can you give an update on this issue?

**Comment by rwcarlsen** [comment]
this is blocked on implementing cep23.

**Comment by gidden** [comment]
to 1.4
