### ISSUE TITLE
FeedQty does not handle non-fissile material

### ISSUE THREAD

**Issue by mbmcgarry** [cyclus/cyclus#1087]
Cyclus::toolkit::FeedQty assumes that input material is only comprised of U235, U238.  It needs to account for the presence of potential non-fissile material, which would require more material to be returned than in the standard case.

**Comment by gidden** [comment]
@mbmcgarry, can this be closed?

**Comment by mbmcgarry** [comment]
Yep, didn’t even realize that was still open!


On Apr 24, 2015, at 11:18 AM, Matthew Gidden <notifications@github.com<mailto:notifications@github.com>> wrote:


@mbmcgarry<https://github.com/mbmcgarry>, can this be closed?
