### ISSUE TITLE
cycpp needs support for recursive container types.

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1097]
Currently, the SchemaFilter is written to assume that all elements of a container type are one of our primitive types.  This assumption is violated for things like `vector<vector<double> >`, `map<string, vector<double> >`, etc.  This would be helpful for the separations facility among other things (which needs to be done soon).  And the sqlite backend now can easily support more container nesting now with #1096.

**Comment by rwcarlsen** [comment]
@scopatz - if you can find a bit of time for this, I might be able to squeeze a bit of time to start making more progress separations.

**Comment by scopatz** [comment]
@rwcarlsen - I likely won't be able to find any time for this in the next week+.  Also, I don't believe that I am the original author of this class.  Refactoring this should to be recursive not be terribly difficult.  There is already a template for how to do this in the InfileToDb class.

**Comment by gidden** [comment]
can this be closed @rwcarlsen ?

**Comment by rwcarlsen** [comment]
Yep.

**Comment by gidden** [comment]
closed with #1098
