### ISSUE TITLE
mock resource exchange

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#1147]
mocking up a resource exchange would help with testing complicated agent-exchange scenarios. combining it with a mock database instance will be critical to confirm expected output.

**Comment by rwcarlsen** [comment]
Fixed by #1076 - right @gidden? Or did you mean something else...

**Comment by gidden** [comment]
The original issue was to mock up the underlying resource exchange. #1076
is one level of abstraction up from that, but likely sufficient for what
was meant here. I'm happy with closing.

On Tue, Aug 25, 2015 at 3:57 PM, Robert Carlsen <notifications@github.com>
wrote:

> Fixed by #1076 <https://github.com/cyclus/cyclus/pull/1076> - right
> @gidden <https://github.com/gidden>? Or did you mean something else...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/issues/1147#issuecomment-134739690>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
If anybody plans on doing this nearish term, they can reopen.
