### ISSUE TITLE
some tests fail on conda install

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#1176]
specifically the discovery-related tests and mocksim tests. this is because the install path is configured in a `.cc` file which is compiled on the building machine, yet the installation involves a copy to the client.

**Comment by rwcarlsen** [comment]
Have the conda recipe updates merged in recently taken care of this? (esp. @scopatz as our conda expert).

**Comment by scopatz** [comment]
I believe that they have. Feel free to close

**Comment by rwcarlsen** [comment]
Fixed by #1214 (hopefully).
