### ISSUE TITLE
conda does not install cmake currently

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#1177]
not at all sure why, but installing cyclus from conda does not result in a cmake executable in $CONDA/bin

**Comment by gidden** [comment]
note that this blocks any sort of `cyclus-deps`-type conda builds

**Comment by rwcarlsen** [comment]
The regular conda packages don't need to and shouldn't install CMake - it is only needed for config/compile - which binary installations don't need.  For the cyclus-deps type package, however, CMake will need to be installed - it probably should just be included as a conda dependency of the cyclus-deps package.

**Comment by gidden** [comment]
It's included as a dependency of both packages, but it should probably be
included as a run-time dependency in the deps pacakge.

On Mon, Jun 1, 2015 at 9:59 PM, Robert Carlsen <notifications@github.com>
wrote:

> The regular conda packages don't need to and shouldn't install CMake - it
> is only needed for config/compile - which binary installations don't need.
> For the cyclus-deps type package, however, CMake will need to be installed
> - it probably should just be included as a conda dependency of the
> cyclus-deps package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/issues/1177#issuecomment-107782379>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
You are quite right sir Matt.  Good disambiguation.

**Comment by gonuke** [comment]
Do we know that the conda install of the cyclus-deps is still a productive path?  I remember seeing that some people had struggles with this more recently?

**Comment by gidden** [comment]
The path was decided to be unproductive on batlab. It is not clear if
quicker iteration and testing would be productive here.

On Tue, Jun 2, 2015 at 9:27 AM, Paul Wilson <notifications@github.com>
wrote:

> Do we know that the conda install of the cyclus-deps is still a productive
> path? I remember seeing that some people had struggles with this more
> recently?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/issues/1177#issuecomment-107972618>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gonuke** [comment]
got it!

**Comment by gidden** [comment]
closed with cyclus/release#72
