### ISSUE TITLE
Multiple traders of a single manager/agent clobber each other

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/cyclus#1209]
This bug was introduced in #1207.  In the DRE stage where traders are iterated over, our custom sorting order doesn't allow for multiple traders to come from a single agent/manager; they instead overwrite each other resulting in bad outcomes.

**Comment by gidden** [comment]
@jlittell, this is the issue that is causing you PR to fail unexpectedly.
When it's fixed, you should be good to go.
