### ISSUE TITLE
Errors in hdf5_back_gen.py

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus#1236]
I am getting the following error when I try to build cyclus on a clean Ubuntu system....  I know there are a lot of issues and discussion around HDF5 right now, but I didn't see anything about this...  @scopatz ? @hodger ?

```
-- Found '/root/cyclus/share/cyclus_nuc_data.h5'
Traceback (most recent call last):
  File "/root/cyclus/src/hdf5_back_gen.py", line 32, in <module>
    CANON_SET.add(convert_canonical(row[7]))
  File "/root/cyclus/src/hdf5_back_gen.py", line 28, in convert_canonical
    return tuple(convert_canonical(x) for x in raw_list)
  File "/root/cyclus/src/hdf5_back_gen.py", line 28, in <genexpr>
...
  File "/root/cyclus/src/hdf5_back_gen.py", line 28, in convert_canonical
    return tuple(convert_canonical(x) for x in raw_list)
  File "/root/cyclus/src/hdf5_back_gen.py", line 28, in <genexpr>
    return tuple(convert_canonical(x) for x in raw_list)
RuntimeError: maximum recursion depth exceeded
```

**Comment by scopatz** [comment]
@hodger, can you take a look please?  Also @gonuke, I still cannot compile / link Cyclus on my main machine.  See #1232.

**Comment by gonuke** [comment]
Note, these errors don't necessarily prevent the build from completing, but I wonder if they are related.  They happen early in the CMake process and may not have been noticed by others???

**Comment by hodger** [comment]
I am going over this, but I can't seem to duplicate that error. When I attempt to install from develop, the hdf5_back.cc seems to build fine, but I get errors from the Google Test.

```
/home/ryan/cyclus/cyclus/tests/GoogleTest/gtest/gtest-all.cc:7833:1: error: ‘GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_’ does not name a type
 GTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS_
 ^
/home/ryan/cyclus/cyclus/tests/GoogleTest/gtest/gtest-all.cc: In function ‘pid_t testing::internal::ExecDeathTestSpawnChild(char* const*, int)’:
/home/ryan/cyclus/cyclus/tests/GoogleTest/gtest/gtest-all.cc:7900:57: error: ‘StackGrowsDown’ was not declared in this scope
     static const bool stack_grows_down = StackGrowsDown();
                                                         ^
/home/ryan/cyclus/cyclus/tests/GoogleTest/gtest/gtest-all.cc: At global scope:
/home/ryan/cyclus/cyclus/tests/GoogleTest/gtest/gtest-all.cc:9475:33: error: expected constructor, destructor, or type conversion before ‘(’ token
 GTEST_DISABLE_MSC_WARNINGS_PUSH_(4996)
                                 ^
/home/ryan/cyclus/cyclus/tests/GoogleTest/gtest/gtest-all.cc:10381:1: error: expected ‘}’ at end of input
 }  // namespace testing
 ^
/home/ryan/cyclus/cyclus/tests/GoogleTest/gtest/gtest-all.cc:10381:1: error: expected ‘}’ at end of input
tests/CMakeFiles/gtest.dir/build.make:62: recipe for target 'tests/CMakeFiles/gtest.dir/GoogleTest/gtest/gtest-all.cc.o' failed
make[2]: *** [tests/CMakeFiles/gtest.dir/GoogleTest/gtest/gtest-all.cc.o] Error 1
CMakeFiles/Makefile2:1117: recipe for target 'tests/CMakeFiles/gtest.dir/all' failed
make[1]: *** [tests/CMakeFiles/gtest.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "install.py", line 162, in <module>
    main()
  File "install.py", line 159, in main
    install_cyclus(args)
  File "install.py", line 86, in install_cyclus
    shell=(os.name == 'nt'))
  File "/home/ryan/miniconda3/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2

```
I'm not familiar with what the Google Test is doing here.

**Comment by hodger** [comment]
@gonuke regarding your traceback, I've executed hdf5_back_gen.py to print to console, but I am not getting any recursion error. I'm going to keep looking to see if its output matches what is expected.

**Comment by gonuke** [comment]
I was on a clean Ubuntu 14.04 system (Rackspace) and then do this:
```
apt-get install -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev git libglib2.0-dev python3-jinja2 python3-pandas-lib python3-numpy python3-matplotlib python3 cython cython3

CYCLUS_ROOT=${HOME}/.local
export PATH=${CYCLUS_ROOT}/bin:${PATH}

# update and install the upstream cyclus develop branch
git clone https://github.com/cyclus/cyclus.git
cd cyclus
git checkout develop
python3 install.py -j 8 --prefix=${CYCLUS_ROOT} |& ~/build.log
```

See the full `build.log` at https://gist.github.com/gonuke/9d6476f67f81e23f2df2

**Comment by gonuke** [comment]
I've repeated the same on clean Ubuntu 15.10 system (also Rackspace), and its build.log is available in the same gist: https://gist.github.com/gonuke/9d6476f67f81e23f2df2

```
apt-get install -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev git libglib2.0-dev python3-jinja2 python3-pandas-lib python3-numpy python3-matplotlib python3 cython cython3

CYCLUS_ROOT=${HOME}/.local
export PATH=${CYCLUS_ROOT}/bin:${PATH}

# update and install the upstream cyclus develop branch
git clone https://github.com/cyclus/cyclus.git
cd cyclus
git checkout develop
python3 install.py -j 8 --prefix=${CYCLUS_ROOT} |& tee ~/build.log
```

**Comment by hodger** [comment]
Just wanted to ping: still working on this issue.

**Comment by hodger** [comment]
@gonuke @scopatz 

I've made headway on this! What I found is that on a fresh install of 14.04, these errors arise from unhandled cases of the Python 2 "unicode" type. 

The convert_canonical function doesn't know what to do with this type and then recurses endlessly. 

Inside the cyclus/src directory, this command:
```python3 hdf5_back_gen.py```
will produce the correct output. 

However, when we try to install Cyclus, even with the ```Python3``` command, it is defaulting to the use of stock Python 2.7.

**Comment by scopatz** [comment]
@hodger the best thing to do is to make sure that the code works with Python 2.7.  Cyclus still supports this version of Python, and so the `hdf5_back_gen.py` script should be Python 2.7 compatible.

**Comment by gonuke** [comment]
I agree with the strategy of ensuring compatibility with Python 2.7, but to explain what @hodger was experiencing....  the CMakeList.txt files invoke `python` in three different places.  Perhaps we should capture the specific version of python that is used to invoke `install.py` and then use that in the CMakeList.txt files??

**Comment by scopatz** [comment]
Ideally, yes, I agree with you @gonuke that the version of Python that install.py was called with should be passed down. In fact, I thought it already was...

**Comment by rwcarlsen** [comment]
@gonuke - can you confirm that this has been fixed - and close accordingly?

**Comment by rwcarlsen** [comment]
ping @gonuke?

**Comment by rwcarlsen** [comment]
I'm closing this as addressed.  Remaining python capturing feature is now in separate issue #1239
