### ISSUE TITLE
Linker issues for cyclus_unit_tests on develop

### ISSUE THREAD

**Issue by scopatz** [cyclus/cyclus#1251]
On a clean build on Ubuntu 15.10 (without conda), I am seeing the following run-time linker error on develop (9065eeae11a59bf22123c0d97d953e883bfda3c2):

```console
(cli-wily)scopatz@localhost:~/cyclus$ cd tests/
(cli-wily)scopatz@localhost:~/cyclus/tests$ cyclus_unit_tests 
cyclus_unit_tests: symbol lookup error: cyclus_unit_tests: undefined symbol: _ZN7testing8internal23MakeAndRegisterTestInfoEPKcS2_S2_S2_NS0_12CodeLocationEPKvPFvvES7_PNS0_15TestFactoryBaseE
```

This seems to be related to gtest in some way. Everything seems to build just fine. Note that on this same machine on `1.3.1` everything builds fine and the tests run and I don't see this issue.

This is preventing me from looking into the pandas stuff as now none of my 5 or so environments actually can build cyclus, even from scratch. @gonuke @opotowsky any ideas?  Has anyone seen this issue?

**Comment by opotowsky** [comment]
I have Ubuntu 15.10, the most recent libgtest-dev installed via apt-get (1.7.0), and cyclus on develop with a clean build. I do not get this linking error.

**Comment by scopatz** [comment]
Thanks for the hint about libgtest-dev. That didn't fix the issue for me and that doesn't seem to be listed in the readme. Is that a dependency now?

**Comment by rwcarlsen** [comment]
This looks like the build is finding outdated gtest headers installed.  You
need to remove the cyclus specific installed gtest headers and lib and then
do a clean build.

**Comment by scopatz** [comment]
@rwcarlsen is it safe to remove gtest from the system completely?

**Comment by scopatz** [comment]
err from the repo?

**Comment by rwcarlsen** [comment]
Cyclus vendors and installs its own gtest in a cyclus specific dir (i.e.
Lib/cyclus/ and include/cyclus/). Those are the ones you need to remove.

**Comment by scopatz** [comment]
Why does it do that though? Can't we rely on a package manager?

**Comment by scopatz** [comment]
Removing that (and the rest of my system) did fix the issue.

**Comment by rwcarlsen** [comment]
This happens sometimes when we revendor/update our internal gtest.  It occurs because our build system (i.e. cmake files) are not crafted carefully enough to prioritize including gtest headers from the cyclus repo/build itself over ones in the install location and/or other system locations.  I'll make an issue.
