### ISSUE TITLE
Build should fail on hdf5_back_gen failures

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus#1287]
Currently, the build process invokes `hdf5_back_gen.py` but ignores failures that may occur when this happens.  These failures are potentially (or always?) fatal to a good build.

We need to either have the build process fail directly, or have tests that will identify the consequences of these failures.

**Comment by Baaaaam** [comment]
is it fixed ?

**Comment by scopatz** [comment]
Yes, by @hodger
