### ISSUE TITLE
unable to compile cyclus

### ISSUE THREAD

**Issue by Baaaaam** [cyclus/cyclus#1311]
there is an issue with cmake I experience it both on ci and my laptop:

> Traceback (most recent call last):
>   File "/cyclus/cyclus/gentypesystem.py", line 998, in <module>
>     main()
>   File "/cyclus/cyclus/gentypesystem.py", line 993, in main
>     ts = setup(ns)
>   File "/cyclus/cyclus/gentypesystem.py", line 962, in setup
>     ver = tuple(map(int, verstr.partition('-')[0].split('.')))
> ValueError: invalid literal for int() with base 10: 'v1'
> CMake Error at cyclus/CMakeLists.txt:17 (message):
>   Generating type system failed (gentypesystem.py), res_var = '1'

this appears when installing using both:
- `python install.py --clean-build`
- `mkdir bld; cd bld; cmake ..`

I don't understand why it is appearing now and was working yesterday before the merge

hopefully @scopatz will have a better idea...

when using the develop version before #1310 merge it is working.

**Comment by Baaaaam** [comment]
the problem come from the version.
on develop and release branch it is not set as v1.4.2-rc1 which it don't like.
did it get the tag name ?

**Comment by Baaaaam** [comment]
the problem comes from a bad tag name: I set it to v1.4.2-rc1 not 1.4.2-rc1...

**Comment by Baaaaam** [comment]
it was the problem.
to fix it I recreated a correct tag name. and suppressed the bad one.

@scopatz: Could you confirm it did not mess up with the `conda` thing ? if so please close this issue.

**Comment by scopatz** [comment]
Seems to work for me!
