### ISSUE TITLE
cyclus python package broke deb generation

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1329]
the actual version of the python package generation for cyclus broke the automatic debian package generation:

> CPack: Create package using DEB
> CPack: Install projects
> CPack: - Run preinstall target for: CYCLUS
> CPack: - Install project: CYCLUS
> ############### Begin Python Install ###############
> -- Python installer:
>   PYTHON_EXECUTABLE: /usr/bin/python
>   CYCLUS_CORE_VERSION: 1.5.0-2-gb54c915
>   CMAKE_INSTALL_PREFIX: /usr/local
>   CMAKE_CURRENT_BINARY_DIR: 
> CMake Error at /cyclus/deb/cmake/SetupPyInstall.cmake:13 (execute_process):
>   execute_process given unknown argument "res_var".
> Call Stack (most recent call first):
>   /cyclus/deb/cmake_install.cmake:63 (INCLUDE)
> 
> 
> CMake Error at /cyclus/deb/cmake/SetupPyInstall.cmake:17 (message):
>   Process setup.py install failed, res_var = ''
> Call Stack (most recent call first):
>   /cyclus/deb/cmake_install.cmake:63 (INCLUDE)

I have generated the debian package manually with those [changes](https://github.com/cyclus/cyclus/compare/master...Baaaaam:temp_fix_deb) in `cmake/SetupPyInstall.cmake.in`.

But those are acceptable to be merged.
@scopatz do you have an idea for a better solution ?

the problem is: `CMAKE_CURRENT_BINARY_DIR` variable is not defined in cpack
as well as `RESULT_VARIABLE res_var` option

**Comment by scopatz** [comment]
Hi @Baaaaam, I think we should have another variable that is set either to the dir you have if we are running CPack and the binary dir if we are not.  

Also getting rid of res_var is not generally OK. Builds should fail ASAP. 

I hope that this makes sense. Please open a PR and we can go from there.

**Comment by gonuke** [comment]
@bennibbelink can review how hard it is to make Debian packages and whether we want to restore this capability.

**Comment by bennibbelink** [comment]
I've found a way to resolve the issue described above about `CMAKE_CURRENT_BINARY_DIR`.  I need to figure out what the appropriate dependency versions are, then we should be in business.  How has the cyclus debian package been distributed in the past?

**Comment by gonuke** [comment]
I think we had the `.deb` file at some location and linked to it from the website.  We didn't have any kind of package repository.
