### ISSUE TITLE
segmentation fault when running unit_test for the first time.

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1334]
I have notice this before, and I forgot to report it.

Sometimes (not all the time) the first time I run the `cyclus_unit_test` after a fresh compilation, I got a segmentation fault:
```
[       OK ] CompMathTests.ApplyThresholdNegative (0 ms)
[ RUN      ] CompMathTests.ApplyThresholdMedium
[1]    75704 segmentation fault  cyclus_unit_tests
```

the second (and all the other one after) works just fine:
```
[----------] Global test environment tear-down
[==========] 560 tests from 109 test cases ran. (14958 ms total)
[  PASSED  ] 560 tests.
```

**Comment by FlanFlanagan** [comment]
To add on to this I'm getting a segmentation fault on the integ_tests.cc tests. 

`[----------] 3 tests from IntegTests
[ RUN      ] IntegTests.RunAllInfiles
Segmentation fault (core dumped)
`
I looked into it and it seems like that segfault is coming from the RunSim() function. 

`TEST(IntegTests, RunAllInfiles) {
  std::vector<std::string> infiles;
  infiles.push_back("custom_dt.xml");
  infiles.push_back("inventory.xml");
  infiles.push_back("inventory_compact.xml");
  infiles.push_back("inventory_compact_false.xml");
  infiles.push_back("inventory_false.xml");
  infiles.push_back("lotka_volterra_determ.xml");
  infiles.push_back("minimal_cycle.xml");
  infiles.push_back("null_sink.xml");
  infiles.push_back("predator.xml");
  infiles.push_back("prey.xml");
  infiles.push_back("source_to_sink.xml");
  infiles.push_back("trivial_cycle.xml");

  for (int i = 0; i < infiles.size(); i++) {
    {
      SqliteBack back(":memory:");
      RunSim(infiles[i], &back);
    }
  }
}
`

**Comment by gonuke** [comment]
I no longer experience these segfaults when running c++ cyclus, so I'm closing this issue.
