### ISSUE TITLE
issue with hdf5_back_gen.py preventing cyclus (develop) installation

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1354]
I tried to update cyclus on my ubuntu desktop (16.04)  and I got:
```
-- Found '/home/mouginot/work/app/cyclus/cyclus/share/cyclus_nuc_data.h5'
  File "/home/mouginot/work/app/cyclus/cyclus/src/hdf5_back_gen.py", line 2247
    body=[*child_bodies,
          ^
SyntaxError: invalid syntax
```

I was able to trace the change that make this between commit #8903790 and #23c29cc, which corresponds to PR #1333.

I am using python 2.7 which might be the source of the issue.
[here](https://gist.github.com/bam241/308fe85667fc848492d7e703920fa7e8) is a gist with my install log

**Comment by scopatz** [comment]
Hi @bam241 - yes, I believe that this is a Python 2 vs 3 issue. @hodger, would you mind taking a look at it, please?

**Comment by bam241** [comment]
closing as this issue is fixed :)
