### ISSUE TITLE
Python3 Instructions for Ubuntu should include update-alternatives

### ISSUE THREAD

**Issue by katyhuff** [cyclus/cyclus#1375]
The default behavior on ubuntu is to ignore that you've installed python3 and various python3 packages... ubuntu will just keep pointing at python2.7 until you tell it to look at your new python3 install. To get ubuntu to use, by default, the python3 the user has just installed we now have to use "update-alternatives" (as here: https://benzidwael.wordpress.com/2015/04/17/installing-different-python-versions-in-ubuntu/) 

Without the update-alternatives step, the build will fail to use python3, even if the user is following the python3 track in the current fuelcycle.org instructions. 

This issue can be closed when the installation docs include a hint about changing the python version (using update-alternatives). This hint should appear after the hint about python -V. http://fuelcycle.org/user/DEPENDENCIES.html#installing-dependencies-linux-and-unix

**Comment by katyhuff** [comment]
The python version information will need to be changed in the docs here:
https://github.com/cyclus/cyclus/blob/develop/DEPENDENCIES.rst

This information should be placed right after :+1: 
```
To determine which version of Python is already installed on your computer, run:

python -V
```

**Comment by skc222** [comment]
Can we close this issue?

**Comment by scopatz** [comment]
Yes, feel free to close it.

**Comment by skc222** [comment]
I think I don't have permissions to do so as I cannot see any button to close issue.
