### ISSUE TITLE
swapping c1 and c2 in ExXlateTests.XlateCapacities

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1377]
Here

https://github.com/cyclus/cyclus/blob/develop/tests/exchange_translator_tests.cc#L151-L155
```
#ifdef __APPLE__
  double rarr[] = {(c1->convert(mat) / qty), (c2->convert(mat) / qty)};
#else
  double rarr[] = {(c2->convert(mat) / qty), (c1->convert(mat) / qty)};
#endif
```

this no longer works with the default clang compiler shipped with the last version of MACOS (10.12 -- Sierra)

**Comment by scopatz** [comment]
Is there any way that we can distinguish between Mac OS versions via a pre-proc variable?

**Comment by bam241** [comment]
I'll look into that, I just posted this to keep a track

**Comment by bam241** [comment]
this is a duplicate of #1376 .

closing this one
