### ISSUE TITLE
#inlcude instead of #include

### ISSUE THREAD

**Issue by emmaredfoot** [cyclus/cyclus#1385]
When building a new archetype, the location_name_tests.cc file has an error in the include statement:

/home/emma/github/cyclus/dual_generation/build/hybrid/dual_generation_tests.cc:8:2: error: invalid preprocessing directive #inlcude
 #inlcude "pyhooks.h"
 ^

**Comment by scopatz** [comment]
Hi @emmaredfoot - thanks for reporting! I don't believe that `location_name_tests.cc` is a file in the cyclus project currently. Are you on some other topical branch other than develop?

**Comment by emmaredfoot** [comment]
Hi @scopatz I think I addressed it and sent a pull request. 

Thanks,

Emma

**Comment by scopatz** [comment]
Let's please leave this open until the fix is merged in. Thanks!
