### ISSUE TITLE
Compile error on macOS from CMake flags

### ISSUE THREAD

**Issue by sskutnik** [cyclus/cyclus#1389]
I can no longer compile Cyclus on macOS Sierra, due to what appears to be unidentified compiler flags that XCode treats as errors. Specifically I get the following errors:

> [  0%] Building C object src/CMakeFiles/cyclus.dir/transmute.c.o
> clang: error: unknown argument: '-fcx-fortran-rules'
> clang: error: unknown argument: '-fcx-limited-range'
> clang: error: unknown argument: '-ftree-sra'
> clang: warning: optimization flag '-ftree-ter' is not supported [-Wignored-optimization-argument]
> clang: warning: optimization flag '-fexpensive-optimizations' is not supported [-Wignored-optimization-argument]

This appears to be introduced by the [introduction of Transmutagen](https://github.com/cyclus/cyclus/commit/6a7077def3dd772284ccd8009a618f52a47a5861) #1383, i.e., the offending flags are in src/CMakeLists.txt, lines 166-168, commited:

```
set_source_files_properties(transmute.c PROPERTIES COMPILE_FLAGS
    "-O0 -fcx-fortran-rules -fcx-limited-range -ftree-sra -ftree-ter -fexpensive-optimizations"
    )
```

Note that Ubuntu doesn't seem to have a problem with this, but clang doesn't know how to process these flags, which will default to an error state. Similarly, if I comment out the above-offending lines, it will compile on macOS (although I assume these flags are included for a specific performance reason).

**Comment by scopatz** [comment]
Hi @sskutnik , thanks for pointing this out!  Out of curiosity, how long does it take to build with no flags installed? Does it seem to take a lot longer?

@asmeurer can you please figure out which flags should be used for clang and transmutagen?

**Comment by scopatz** [comment]
A potential fix is in #1392

**Comment by scopatz** [comment]
Note that the fix in #1392 is just a temporary solution to reallow transmutagen to compile. We still need the compiler flags for this @asmeurer :)

**Comment by asmeurer** [comment]
I looked around, but I couldn't find anything that helps other than `-ffast-math`. Sadly, even with this, it is about 4x slower than with GCC. I tried `-O1`, but then the compilation doesn't finish. I'll keep looking to see if I can find anything else.

**Comment by asmeurer** [comment]
`-O1` compilation eventually crashed with `fatal error: error in backend: IO failure on output stream.`

**Comment by asmeurer** [comment]
Upon further testing and researching, I'm not even sure if -ffast-math is doing anything. I tried the suggestion from http://clang-developers.42468.n3.nabble.com/Complex-arithmetic-ignores-ffast-math-after-clang-r219557-serious-performance-regressions-td4046207.html, but it made it even slower. 

I'll keep looking, but for now, just use `-O0` (needed to compile without hanging/crashing), `-ffast-math` (could be a placebo), and accept that it will be 4x slower with clang than GCC.

**Comment by scopatz** [comment]
Thanks @asmeurer!

**Comment by scopatz** [comment]
Can you add that to the message that is printed at the end of transmutagen output, please? Thanks!
