### ISSUE TITLE
Question related to python binding

### ISSUE THREAD

**Issue by orpheus92** [cyclus/cyclus#1397]
Hi all, I have a question related to the python binding. 
When I try to run a simulation on of the the input scenario by python -m cyclus input.json in the command line, it reported an error related to the file simstate.py
The errors are shown as following: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/orpheus92/.local/lib/python3.5/site-packages/cyclus/__main__.py", line 2, in <module>
    main()
  File "/home/orpheus92/.local/lib/python3.5/site-packages/cyclus/main.py", line 427, in main
    run_simulation(ns)
  File "/home/orpheus92/.local/lib/python3.5/site-packages/cyclus/main.py", line 402, in run_simulation
    state.load()
  File "/home/orpheus92/.local/lib/python3.5/site-packages/cyclus/simstate.py", line 136, in load
    self._load_schema_path()
  File "/home/orpheus92/.local/lib/python3.5/site-packages/cyclus/simstate.py", line 173, in _load_schema_path
    if schema_type == "flat" and not ns.flat_schema:
NameError: name 'ns' is not defined
```

I am using the latest develop branch of cyclus.

**Comment by orpheus92** [comment]
{
 "simulation": {
  "agent": {"name": "deployer1", "prototype": "optim_deployer"}, 
  "archetypes": {
   "spec": [
    {"lib": "cycamore", "name": "Source"}, 
    {"lib": "cycamore", "name": "DeployInst"}, 
    {"lib": "cycamore", "name": "Sink"}, 
    {"lib": "cycamore", "name": "Enrichment"}, 
    {"lib": "cycamore", "name": "Reactor"}, 
    {"lib": "cycamore", "name": "Storage"}, 
    {"lib": "cycamore", "name": "FuelFab"}, 
    {"lib": "cycamore", "name": "Separations"}
   ]
  }, 
  "control": {"decay": "never", "duration": "2400", "startmonth": "1", "startyear": "2000"}, 
  "prototype": [
   {
    "config": {
     "Storage": {"incommod": "slow_spent", "outcommod": "slow_spent_stored", "wait_time": "84"}
    }, 
    "name": "slow_storage"
   }, 
   {
    "config": {
     "Storage": {"incommod": "fast_spent", "outcommod": "fast_spent_stored", "wait_time": "84"}
    }, 
    "name": "fast_storage"
   }, 
   {
    "config": {
     "Enrichment": {
      "feed_commod": "natl_u", 
      "feed_recipe": "natl_u", 
      "initial_feed": "1e100", 
      "product_commod": "uox", 
      "swu_capacity": "1e100", 
      "tails_assay": "0.0025", 
      "tails_commod": "waste"
     }
    }, 
    "name": "enrichment"
   }, 
   {
    "config": {
     "Separations": {
      "feed_commods": {"val": "slow_spent_stored"}, 
      "feedbuf_size": "107537", 
      "leftover_commod": "waste", 
      "streams": {
       "commod": "slow_pu", 
       "info": {"buf_size": "1e100", "efficiencies": {"comp": "Pu", "eff": ".99"}}
      }, 
      "throughput": "83333.3333"
     }
    }, 
    "name": "slow_separations"
   }, 
   {
    "config": {
     "Separations": {
      "feed_commods": {"val": "fast_spent_stored"}, 
      "feedbuf_size": "1e100", 
      "leftover_commod": "waste", 
      "streams": {
       "commod": "fast_pu", 
       "info": {"buf_size": "1e100", "efficiencies": {"comp": "Pu", "eff": ".99"}}
      }, 
      "throughput": "1e100"
     }
    }, 
    "name": "fast_separations"
   }, 
   {
    "config": {
     "FuelFab": {
      "fill_commod": "depleted_u", 
      "fill_recipe": "depleted_u", 
      "fill_size": "1e100", 
      "fiss_commod_prefs": {"val": ["1.0", "2.0"]}, 
      "fiss_commods": {"val": ["slow_pu", "fast_pu"]}, 
      "fiss_size": "1e100", 
      "outcommod": "fast_fuel", 
      "spectrum": "fission_spectrum_ave", 
      "throughput": "1e100"
     }
    }, 
    "name": "fastfab"
   }, 
   {
    "config": {
     "Reactor": {
      "assem_size": "29565", 
      "cycle_time": "18", 
      "fuel_incommods": {"val": "uox"}, 
      "fuel_inrecipes": {"val": "uox"}, 
      "fuel_outcommods": {"val": "slow_spent"}, 
      "fuel_outrecipes": {"val": "uox_spent"}, 
      "n_assem_batch": "1", 
      "n_assem_core": "3", 
      "power_cap": "900", 
      "refuel_time": "0"
     }
    }, 
    "lifetime": "960", 
    "name": "slow_reactor"
   }, 
   {
    "config": {
     "Reactor": {
      "assem_size": "7490", 
      "cycle_time": "14", 
      "fuel_incommods": {"val": "fast_fuel"}, 
      "fuel_inrecipes": {"val": "fast_fuel"}, 
      "fuel_outcommods": {"val": "fast_spent"}, 
      "fuel_outrecipes": {"val": "fast_spent"}, 
      "n_assem_batch": "1", 
      "n_assem_core": "5", 
      "power_cap": "360", 
      "refuel_time": "0"
     }
    }, 
    "lifetime": "960", 
    "name": "fast_reactor"
   }, 
   {
    "config": {"Sink": {"capacity": "1e100", "in_commods": {"val": "waste"}}}, 
    "name": "repo"
   }, 
   {
    "config": {
     "Source": {"outcommod": "depleted_u", "outrecipe": "depleted_u", "throughput": "1e100"}
    }, 
    "name": "depleted_src"
   }, 
   {
    "config": {
     "DeployInst": {
      "build_times": {"val": "{{.Time}}"}, 
      "lifetimes": {"val": "{{.Lifetime}}"}, 
      "n_build": {"val": "{{.N}}"}, 
      "prototypes": {"val": "{{.Proto}}"}
     }
    }, 
    "name": "optim_deployer"
   }
  ], 
  "recipe": [
   {
    "basis": "mass", 
    "name": "depleted_u", 
    "nuclide": [{"comp": "0.0025", "id": "U235"}, {"comp": "0.9975", "id": "U238"}]
   }, 
   {
    "basis": "mass", 
    "name": "natl_u", 
    "nuclide": [{"comp": "0.711", "id": "U235"}, {"comp": "99.289", "id": "U238"}]
   }, 
   {
    "basis": "mass", 
    "name": "uox", 
    "nuclide": [{"comp": "0.042", "id": "U235"}, {"comp": "0.958", "id": "U238"}]
   }, 
   {
    "basis": "mass", 
    "name": "fast_fuel", 
    "nuclide": [{"comp": "0.9236", "id": "U238"}, {"comp": "0.0764", "id": "Pu239"}]
   }, 
   {
    "basis": "mass", 
    "name": "fast_spent", 
    "nuclide": [
     {"comp": "0.859", "id": "U238"}, 
     {"comp": "0.0902", "id": "Pu239"}, 
     {"comp": "0.0013", "id": "Am241"}, 
     {"comp": "0.006770", "id": "La139"}, 
     {"comp": "0.006525", "id": "Ce140"}, 
     {"comp": "0.006121", "id": "Ce142"}, 
     {"comp": "0.006550", "id": "Pr141"}, 
     {"comp": "0.004830", "id": "Nd143"}, 
     {"comp": "0.004291", "id": "Nd144"}, 
     {"comp": "0.002968", "id": "Nd145"}, 
     {"comp": "0.002985", "id": "Nd146"}, 
     {"comp": "0.002189", "id": "Nd148"}
    ]
   }, 
   {
    "basis": "mass", 
    "name": "uox_spent", 
    "nuclide": [
     {"comp": ".008", "id": "U235"}, 
     {"comp": "0.9268", "id": "U238"}, 
     {"comp": "0.012", "id": "Pu239"}, 
     {"comp": "0.0011", "id": "Am241"}, 
     {"comp": "0.005866", "id": "La139"}, 
     {"comp": "0.005911", "id": "Ce140"}, 
     {"comp": "0.005727", "id": "Ce142"}, 
     {"comp": "0.005652", "id": "Pr141"}, 
     {"comp": "0.005103", "id": "Nd143"}, 
     {"comp": "0.005708", "id": "Nd144"}, 
     {"comp": "0.005102", "id": "Nd146"}
    ]
   }
  ], 
  "schematype": "flat"
 }
}
This is the input file I am using in the format of json

**Comment by scopatz** [comment]
Hi @orpheus92 - this seems like a bug. I'll look into it.

**Comment by scopatz** [comment]
Thanks for reporting @orpheus92! A fix is now available in #1398

**Comment by orpheus92** [comment]
What about line 175 "file=sys.stderr" in the same file?

**Comment by scopatz** [comment]
that should not be a problem

**Comment by scopatz** [comment]
Should be good to go now.

**Comment by orpheus92** [comment]
Do we need to add import sys at the beginning of simstate.py?

**Comment by scopatz** [comment]
Are you seeing another error?

**Comment by orpheus92** [comment]
Sys module is used in line 175 but not defined. It reports the error when I run it. that is why I add import sys at the beginning.

**Comment by scopatz** [comment]
Yes, then.  Please PR a fix in! Thanks!

**Comment by orpheus92** [comment]
Closing this now.
