### ISSUE TITLE
Unable to find HDF5 Library

### ISSUE THREAD

**Issue by gyutaepark** [cyclus/cyclus#1408]
@scopatz 
I've tried to build Cyclus using the latest develop on Ubuntu 16.04 with anaconda installed. Unfortunately, there seems to be issues with finding the correct libraries, especially HDF5. I've tried the following versions of HDF5: 1.8.16, and 1.8.17.

This issue with building Cyclus did not exist when I tried building from `v1.4.2-release`.

Could you look into this please?

I've also attached a text file of the build message.
[return message.txt](https://github.com/cyclus/cyclus/files/1211431/return.message.txt)

**Comment by scopatz** [comment]
Thanks for reporting @gyutaepark. What conda channels are you building based off of? I am using conda-forge, which I think has more updated versions of cmake and HDF5.

**Comment by scopatz** [comment]
Also, did you do a clean build? Also what line did you use at the command line? Also do you have the `cyclus-build-deps` package installed? This is part of conda-forge and needed for building cyclus on top of a conda installation.

**Comment by gyutaepark** [comment]
Oops sorry for the confusion. I'm building _CYCLUS_ from source. It's just that my python library is set up with Anaconda 3.

I've also tried a clean build but that did not help.
I am using the following line to build cyclus from source.
`python install.py --clean-build`

**Comment by scopatz** [comment]
What does `conda list cyclus-build-deps` say?

**Comment by gyutaepark** [comment]
Hmmm it returns nothing..
```
# packages in environment at /home/user/anaconda3:
#
```

**Comment by scopatz** [comment]
right, so you should/need to install that package to be able to build Cyclus. I also recommend that you add the conda-forge channel to your condarc file

**Comment by gyutaepark** [comment]
Alright will do! Thanks for the help. I was just confused because this has not happened before.

**Comment by gyutaepark** [comment]
Installing `cyclus-build-deps` did work really well for me!
However, I'm still not sure why this error hasn't come up before or if this issue is just happening to me.
This was a clean Ubuntu (where I just installed Ubuntu for a new PC) and I've successfully installed Cyclus without having to install `cyclus-build-deps` through conda-forge.
Can someone that hasn't installed `cyclus_build~deps` try building from the latest develop to see if this issue is reproducible?
Or would it be better to just add this to the documentation?

**Comment by gyutaepark** [comment]
Actually, it seems like installing `cyclus-build-deps` on conda would be a good practice in general.

**Comment by gyutaepark** [comment]
I'll close this since installing cyclus-build-deps allows cyclus to be installed.
However, the recent update still has introduced an issue when installing cyclus without cyclus-build-deps.

Before, I was able to install cyclus without it. Unless, this was not intended, maybe it is something to be looked at later?

**Comment by scopatz** [comment]
Hi @gyutaepark - when building with conda, it is expected that cyclus-build-deps is used. I would not expect the build to work if this package is not installed and that use case is not supported (by me :smile:)

**Comment by scopatz** [comment]
Thanks for closing!
