### ISSUE TITLE
Failed Tests when running Cyclus_unit_tests

### ISSUE THREAD

**Issue by gwenchee** [cyclus/cyclus#1429]
I am encountering a test failure when running cyclus_unit_tests after installling Cyclus: 
[  FAILED  ] ExXlateTests.XlateCapacities (0 ms)
AND 
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ExXlateTests.XlateCapacities

Details about my computer and installation:
Computer: Mac 
Cyclus Installation: I installed Cyclus from Github, using the steps found: http://fuelcycle.org/user/install_from_git.html
Dependency Installation: I used homebrew to install all the dependencies. I had an issue finding the homebrew installation for the dependency, libxmlxx2. But managed to brew install libxml++ (which i assumed was the equivalent)

**Comment by bam241** [comment]
could you provide a full installation log ?

I feel like this issue might be related to #1376

**Comment by bam241** [comment]
btw `libxml++` and `libxml2` are not the same , but `libxml2` is a dependency of `libxml++` so installing the later will probably install the first one

**Comment by gwenchee** [comment]
Best way to install Cyclus on mac is using conda forge. ``` cyclus_unit_tests ``` will pass when the method is used.
