### ISSUE TITLE
'ctx' has incorrect type

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1436]
running unit test on archetypes I got:

```
Traceback (most recent call last):
  File "lib.pyx", line 1261, in cyclus.lib.capsule_agent_to_py
  File "lib.pyx", line 1264, in cyclus.lib.capsule_agent_to_py
  File "lib.pyx", line 1280, in cyclus.lib.agent_to_py
TypeError: Argument 'ctx' has incorrect type (expected cyclus.lib._Context, got PyCapsule)
Exception ignored in: 'pymodule.py_call_listeners'
Traceback (most recent call last):
  File "lib.pyx", line 1261, in cyclus.lib.capsule_agent_to_py
  File "lib.pyx", line 1264, in cyclus.lib.capsule_agent_to_py
  File "lib.pyx", line 1280, in cyclus.lib.agent_to_py
TypeError: Argument 'ctx' has incorrect type (expected cyclus.lib._Context, got PyCapsule)
```

@scopatz @FlanFlanagan I feel like it could be related to #1434 and/or #1435 
(You can get the same running `cycamore_unit_test`)

**Comment by FlanFlanagan** [comment]
Hmm, I can't seem to replicate this error. This would be in relation to what we did though.

You're on the most recent version of master?

**Comment by FlanFlanagan** [comment]
Oh sorry, looking back at the actual log I do see this. However, it's not blocking the tests for me (which is why I missed it).

**Comment by bam241** [comment]
it is not blocking the test, just popup a msg

**Comment by FlanFlanagan** [comment]
Can you add it as an issue and assign me to it? I'll try and see if I can't figure out the cause when I get some time.

**Comment by scopatz** [comment]
Seems like we are not pulling the ctx out of the capsule

**Comment by bam241** [comment]
I don't see this anymore, using latest master.

Closing.
