### ISSUE TITLE
defining a new enter_notify in a python archetype throws an error. 

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cyclus#1440]
I attempted to extend the enter_notify of an institution (python module), I implemented this inside of the class.

```python
    def enter_notify():
        super().enter_notify()
```

This returned an error citing that an argument is given to the enter_notify function when it expects none. I assume this is because I defined the function within the class, but I'm not sure where else I would define it. 

TypeError: enter_notify() takes 0 positional arguments but 1 was given
Exception ignored in: 'CyclusInstitutionShim.EnterNotify'

**Comment by scopatz** [comment]
This is a method, so you need to include self, which is the 1 expected argument.

```python
def enter_notify(self):
    super().enter_notify()
```

**Comment by FlanFlanagan** [comment]
Yeah...brain fart. 

Closing this.
