### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1450]
with the last version of master `0623719a` when trying to run the `cyclus_unit_test` I got:
```
$>cyclus_unit_tests
dyld: Library not loaded: libagents.dylib
  Referenced from: /Users/mouginot/.local/bin/cyclus_unit_tests
  Reason: image not found
[1]    19075 abort      cyclus_unit_tests
```

reverting to `ef22fb69` don't experience this anymore.
@scopatz it seems to be related to the CRAM thing. 

It might be a local problem, but my LD_LIBRARY_PATH is set properly as well as my PATH...
Any idea how to fix it?

**Comment by bam241** [comment]
@scopatz I guess it is because of #1443

I guess it is a bad configuration on my side...
Any idea how to fix this ?

**Comment by bam241** [comment]
And we probably need to update the install docs...

**Comment by scopatz** [comment]
I am working on this @bam241 - but for now you can set `$DYLD_FALLBACK_LIBRARY_PATH = '/Users/mouginot/.local/lib/cyclus'`

This has to do with the fact that we install agents to lib/cyclus, and only is a problem on Mac.

**Comment by bam241** [comment]
Make sense !
maybe we can add some symb-link on mac to `/Users/mouginot/.local/lib` ?

**Comment by scopatz** [comment]
Well the point of putting agents in the `lib/cyclus` dir is so that they are discoverable and don't clutter up `lib/` itself. We should probably fix this the right way :)
