### ISSUE TITLE
cycstub docs

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1456]
cycstub allows to generate a directory with the basis to build its own archetypes.

cycstub options/flag does not appear on:
`cyclus --help`

**Comment by gyutaepark** [comment]
@bam241 Hi,
Should cycstub options/ flags appear on `cyclus --help`?

Cycstub is present as a separate executable from Cyclus and as far as I know,
creating a directory with the basis to build archetypes is performed with the command:
`cycstub --type {facility, inst, region} [path]:[library-name]:[archetypename]`

This does show up upon calling `cycstub -h`.

**Comment by bam241** [comment]
@gyutaepark you're right... I was somehow confused....
anyway we need to document it on the website...
