### ISSUE TITLE
Issues installing Cyclus/Cycamore (Unit Tests)

### ISSUE THREAD

**Issue by bellis6** [cyclus/cyclus#1457]
Hi, I'm reinstalling Cyclus and Cycamore onto my personal PC.  I reinstalled ubuntu 16.04 on my computer and only executed the following commands into my terminal:

First I installed Anaconda 3 from the terminal

```
cd /tmp
sudo apt install curl
curl -O https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
sha256sum Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh
source ~/.bashrc
```

Then, from [http://fuelcycle.org/user/install_binary.html], I installed Cyclus and Cycamore using the following commands:

```
conda install -c conda-forge cyclus cycamore
cyclus_unit_tests
cycamore_unit_tests
```

However, I am receiving the following output from the unit tests...

```
cyclus_unit_tests: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
cycamore_unit_tests: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
```
Has anyone else experienced this issue?
@katyhuff

**Comment by scopatz** [comment]
Hi @bellis6 - thanks for reporting.  Can you try `conda install libiconv`?  You may need to do the following:

```console
$ conda config --add channels conda-forge
$ conda update --all --update-deps
```

**Comment by bellis6** [comment]
Thank you.  It worked!

**Comment by scopatz** [comment]
Woohoo! Awesome!

**Comment by scopatz** [comment]
maybe we should add those steps to the docs
