### ISSUE TITLE
version 'CXXABI_1.3.X' not found error 

### ISSUE THREAD

**Issue by chiudaniels** [cyclus/cyclus#1473]
-------------------- Creating issue to post solution ------------------------------

When trying to run cyclus_unit_test after an installation of Cyclus the error occurs: 

> cyclus_unit_tests: /home/daniel/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/daniel/anaconda2/bin/../lib/libicui18n.so.58)
cyclus_unit_tests: /home/daniel/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/daniel/anaconda2/bin/../lib/libicui18n.so.58)
cyclus_unit_tests: /home/daniel/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/daniel/anaconda2/bin/../lib/libicuuc.so.58)
cyclus_unit_tests: /home/daniel/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/daniel/anaconda2/bin/../lib/libicuuc.so.58)

**Comment by chiudaniels** [comment]
**Solution**

find the anaconda/lib folder and in it find the file libstdc++.so.6.0.24 
`cd ~/anaconda2/lib`
`ls libstdc++.so.6.0.24`
find the symlink file libstdc++.so.6 in the lib folder
`ls libstdc++.so.6`
remove the symlink file libstdc++.so.6
`rm ~/anaconda3/lib/libstdc++.so.6`
then relink it to the newer version libstdc++.so.6.0.24 
`ln -s libstdc++.so.6.0.24 libstdc++.so.6`

**Comment by morawi** [comment]
That did not help at all, 1) running apt-get update to update all the package lists, followed by apt-get upgrade to update all the installed software to the latest versions and 2) running pip install opencv-contrib-python solved the problem.

**Comment by bam241** [comment]
thx for letting us know !
