### ISSUE TITLE
Archetype Development Tutorial - Python is missing material trading section

### ISSUE THREAD

**Issue by jbae11** [cyclus/cyclus#1475]
In the python archetype development tutorial, the section about material trading is missing.

In my experience, writing `get_material_bids`, `get_material_trades` and so on are not quite intuitive when developing an archetype in python.

This issue can be closed when there is an addition to the documentation on archetype development in python with regards to material trading

**Comment by scopatz** [comment]
Thanks for bringing this up.  First, this should be opened on the docs repo and closed here, probably :) Secondly, all of the Python guides for the DRE are available on the [DRE page](http://fuelcycle.org/arche/dre.html).  The C++ and Python Tutorial pages should be effectively the same, just with different language implementations.  I agree that the tutorials could be improved in this regard.

**Comment by jbae11** [comment]
That definitely did! Solved my issue. But it would be helpful if the Python develop still referenced to the DRE page. I will close this issue and make another one regarding this on the cyclus docs repo! Thanks @scopatz
