### ISSUE TITLE
Activity's units

### ISSUE THREAD

**Issue by KennellyT** [cyclus/cyclus#1478]
Hey cyclus team, 
After running a cyclus simulation I went to see the activity of the SNF. I went through the documentation to find the units in which activity is given and I could not find its units. I know that cyclus bases its decay heat and activity off of pyne so I tried its [documentation](http://pyne.io/pyapi/material.html?highlight=activity#pyne.material.Material.activity) but I was unable to find activity's units there either. 
What are the units of activity within cyclus?

**Comment by bam241** [comment]
Hi Tyler,

From what I see in Pyne http://pyne.io/pyapi/data.html?highlight=decay_const#pyne.data.decay_const <http://pyne.io/pyapi/data.html?highlight=decay_const#pyne.data.decay_const>, and Cymetric source code: https://github.com/cyclus/cymetric/blob/master/cymetric/metrics.py <https://github.com/cyclus/cymetric/blob/master/cymetric/metrics.py>

I believe the activity is provided in decay per second so Bq, and the decay heat in MJ/s (so MW)

Baptiste

------------------------------------
Baptiste Mouginot, PhD
Assistant Scientist, Nuclear Engineering
University of Wisconsin-Madison
mouginot.baptiste@gmail.com <mailto:mouginot.baptiste@gmail.com>

**Comment by KennellyT** [comment]
Thank you Baptiste @bam241 
That resolves my questions.
