### ISSUE TITLE
python `record_time_series` clashes with cycamore::Reactor

### ISSUE THREAD

**Issue by jbae11** [cyclus/cyclus#1488]
Calling `lib.record_time_series('POWER', self, power_cap)` in a python archetype clashes with the cycamore::Reactor ` cyclus::toolkit::RecordTimeSeries<cyclus::toolkit::POWER>(this, power_cap);`, and gives an error that says:
```
^^SQL error: CREATE TABLE TimeSeriesPOWER (SimId BLOB, AgentId INTEGER, Time INTEGER, Value REAL); table TimeSeriesPOWER already exists
```

This stems from the [cyclus/lib.pyx](https://github.com/cyclus/cyclus/blob/master/cyclus/lib.pyx) not recognizing `POWER` as a string, but  a TimeSeriesType.

**Comment by FlanFlanagan** [comment]
Can you explain the issue more closely. 

Is it trying to create TimeSeriesPOWER for cycamore twice?

**Comment by jbae11** [comment]
Yeah, I think it's more appropriate to have this issue in cyclus/cyclus, since it is more of a cyclus framework problem than a problem in Cycamore.  You can close this issue if you want!

**Comment by FlanFlanagan** [comment]
issue moved to cyclus/cyclus
