### ISSUE TITLE
Nonfunctional (sort of?) Cyclus Installation

### ISSUE THREAD

**Issue by kipk49** [cyclus/cyclus#1524]
![Cyclus_Error](https://user-images.githubusercontent.com/50880873/60540047-d1004880-9cd3-11e9-974c-23ab728621c6.png)
Installed Cyclus on a fresh Ubuntu machine (previous installation failed, had to reinstall Ubuntu and start from scratch).

Utilized Greg's build script to install dependencies, found at https://github.com/gtw2/setmyenv
Used apt instead of conda; using conda on the first attempted install did not work.

_Note_: to get the installation to work, we had to delete Prey and Predator .cc and .h files, as well as their corresponding mentions in cmake.

This installation of Cyclus passes all unit tests except for 3: DiscoveryTests.DiscoverSpec, DiscoveryTests.DiscoverSpecsInInstallPath, and IntegTests.RunnAllInfiles

Since I am new to Cyclus, I started off by making some simple scenarios; these can be found at https://github.com/kipk49/tests in the testing_area branch. All of these are based off of https://github.com/arfc/transition-scenarios/blob/master/input/eg01-eg23/eg01-eg23-complex.xml. Test 1 is source --> reactor --> sink, test 2 adds an enrichment plant, and test 3 adds a storage pool for the LWR. Test 4 is an attempt to add a reprocessing plant, but it causes Cyclus to fail and generate a large error message. Running the original ARFC transition scenario causes the same message to show up. If I take the reprocessing plant out, everything runs fine.

Test 4 and the original transition scenario both run fine on other computers.

Edit: Added a screenshot of the start of the error message.

**Comment by bam241** [comment]
could you tell us which ubuntu version you are using ?

**Comment by kipk49** [comment]
16.04 LTS

**Comment by bam241** [comment]
I am currently testing a build on a fresh ubuntu 16.04 to see if I can reproduce your problem...


could tell me which of the example you were trying to run ?

note : usually prefer the will log (as a text) to a screenshot :) there is more information in it.
you can upload them on [gist](https://gist.github.com) and get us a link :)

**Comment by kipk49** [comment]
Attempted to run test4.xml and test4B.xml, both cause the same error. It does not crash on Roberto's computer (also on 16.04).

Attached is .txt file with the entire error message.
[Error_Message.txt](https://github.com/cyclus/cyclus/files/3351992/Error_Message.txt)

**Comment by bam241** [comment]
on the ubuntu 16.04 I did (one of the problem you might be encountering is that u-16.04 have python2 by default...):
- `apt-get install -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev python3-dev python3-tables python3-pandas python3-numpy python3-nose python3-jinja2 cython3`
- `apt-get install git openssh-client`
- `git clone https://github.com/cyclus/cyclus.git`
- `apt-get install python3-pip` <- required to install Cython update
- `pip3 install cython==0.26 --force-reinstall`
-`update-alternatives --install /usr/bin/python python /usr/bin/python3.5 2` < force the system to use `pyton3.5`
- `python3 install.py` from the `cyclus` source directory
- `git clone https://github.com/cyclus/cycamore.git`
-  `python3 install.py`
got the same issue :(

**Comment by bam241** [comment]
same issue with 16.04 and 18.04....

**Comment by kipk49** [comment]
Tried with a fresh install, and the same commands you used... Separations seems to be the problem

**Comment by bam241** [comment]
do you know which part of the separations ?

**Comment by kipk49** [comment]
Afraid not

**Comment by gtw2** [comment]
I've replicated this bug on a new user account as well, it seems that the Separations facility gets a "double free or corruption" error on line 137/138
`      streambufs[name].Push(
          mat->ExtractComp(qty * maxfrac, m->comp()));`

Not sure why this is happening, as I've been using separations for a long time without running into this

**Comment by robfairh** [comment]
I reinstalled in a fresh ubuntu (16.04 LTS) cyclus and cycamore, first using their master branches and then with older versions that I've forked to my github and we still get the same error.

[error.txt](https://github.com/cyclus/cyclus/files/3356262/error.txt)

**Comment by kipk49** [comment]
After much trial and error:

The APT set of dependencies in Greg's script allow Cyclus to install correctly (provided that you remove Predator and Prey, as well as their corresponding mentions in the CMake file), but this verison of Cyclus throws the error when dealing with the Separations archetype.

The Conda set of dependencies harnessed by the script (cyclus-build-deps) causes install.py to fail; it seems that the version of numpy installed by cyclus-build-deps is defective. If you attempt to do
`python`
`import numpy`
`numpy.__version__`
there is an error thrown, saying that this copy of numpy has no attribute called "version".

I removed and then reinstalled numpy through Conda; if I run the install.py script again I get an error telling me CMake is not installed. After installing CMake manually, the install.py script tells me I don't have a working C compiler. I'm not entirely sure where to go from here...

**Comment by bam241** [comment]
I am about the update the Conda recipes. It should be working after :)

In the mean time here a list of Conda packages (with proper version) that should be working
conda install -y openssh gxx_linux-64 gcc_linux-64 cmake make docker-pycreds git xo python-json-logger \
python=3.6 glibmm glib=2.56 libxml2 libxmlpp libblas \
libcblas liblapack pkg-config coincbc=2.9 boost-cpp hdf5 \
sqlite pcre gettext bzip2 xz setuptools nose pytables \
pandas jinja2 cython==0.26 websockets pprintpp
BaM 
from my phone

**Comment by robfairh** [comment]
Hopefully that works! We'll try it tomorrow!

**Comment by kipk49** [comment]
Close, but no cigar. Starting with clean install of Ubuntu, I used Greg's script to install Conda (no dependencies) and then did 
`conda install -y openssh gxx_linux-64 gcc_linux-64 cmake make docker-pycreds git xo python-json-logger python=3.6 glibmm glib=2.56 libxml2 libxmlpp libblas libcblas liblapack pkg-config coincbc=2.9 boost-cpp hdf5 sqlite pcre gettext bzip2 xz setuptools nose pytables pandas jinja2 cython==0.26 websockets pprintpp`

Received the following error:
[preyerror.txt](https://github.com/cyclus/cyclus/files/3383374/preyerror.txt)

Manually removed prey & predator .cc and .h files, and then removed their corresponding mentions in cmake file.

Received the following error at 88% (Linking CXX executable ../bin/cyclus_unit_tests):
[boosterror.txt](https://github.com/cyclus/cyclus/files/3383381/boosterror.txt)

Manually installed the "boost" package with Conda (the mass install only installs boost-cpp, I thought regular boost would fix it) and received the same error that mentions boost, still at the 88% mark.

**Comment by bam241** [comment]
could you get a clean conda, do not use any script and just use the conda line ?

it should be working :)

**Comment by robfairh** [comment]
I did this: 
- downloaded conda from the website
https://www.anaconda.com/distribution/#download-section
- bash Anaconda3-2019.03-Linux-x86_64.sh
- echo 'export PATH="~/anaconda/bin:$PATH"' >> ~/.bashrc
- source .bashrc

- conda install -y openssh
- conda install -y gxx_linux-64 gcc_linux-64
- conda install -y cmake make docker-pycreds git xo
- conda install -y python-json-logger python=3.6
- conda install -y sqlite pcre gettext bzip2 xz setuptools nose pytables pandas jinja2 cython==0.26 websockets pprintpp
- conda install -y pkg-config coincbc=2.9 boost-cpp hdf5
- conda install -y libxml2 libxmlpp libblas libcblas liblapack
- conda install -c conda-forge glibmm
- conda install -c conda-forge glib

It didn't complete the installation of cyclus:
[cyclusinstallation.txt](https://github.com/cyclus/cyclus/files/3389088/cyclusinstallation.txt)

This is the outputs of the installation of all the dependencies with conda:
[condainstallation.txt](https://github.com/cyclus/cyclus/files/3389090/condainstallation.txt)

The issue is the same to what kip found. I didn't have any issues with prey and predator.

**Comment by bam241** [comment]
thx for the attempt.
But... because you did not run a single Conda line, the later Conda install might have overwritten some of the previous package.

would you mind trying the same, but with everything in a single Conda install line ?

**Comment by robfairh** [comment]
I did that and this is the result:

(base) kip@kip-arfc:~$ conda install -y openssh gxx_linux-64 gcc_linux-64 cmake make docker-pycreds git xo python-json-logger python=3.6 glibmm glib=2.56 libxml2 libxmlpp libblas libcblas liblapack pkg-config coincbc=2.9 boost-cpp hdf5 sqlite pcre gettext bzip2 xz setuptools nose pytables pandas jinja2 cython==0.26 websockets pprintpp
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - websockets
  - pprintpp
  - xo
  - liblapack
  - libcblas
  - openssh
  - coincbc=2.9
  - libxmlpp
  - python-json-logger
  - libblas
  - glibmm

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I downloaded conda from the website:
https://www.anaconda.com/distribution/#download-section

Then I did:
- bash Anaconda3-2019.03-Linux-x86_64.sh
- echo 'export PATH="~/anaconda/bin:$PATH"' >> ~/.bashrc
- source .bashrc
- conda install -y openssh gxx_linux-64 gcc_linux-64 cmake make docker-pycreds git xo python-json-logger python=3.6 glibmm glib=2.56 libxml2 libxmlpp libblas libcblas liblapack pkg-config coincbc=2.9 boost-cpp hdf5 sqlite pcre gettext bzip2 xz setuptools nose pytables pandas jinja2 cython==0.26 websockets pprintpp

This is the whole message:
[output.txt](https://github.com/cyclus/cyclus/files/3392726/output.txt)

**Comment by bam241** [comment]
thx for trying...

that's weird....

and could you try to install the reps using `cyclus-build-deps` this should allow you to get the correct dependencies...
btw what system are you using ? ubuntu ? 18.04 ?

**Comment by robfairh** [comment]
(base) kip@kip-arfc:~$ conda install -y  cyclus-build-deps
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cyclus-build-deps

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by bam241** [comment]
```
conda config --add channels conda-forge
conda install cyclus-build-deps
```

**Comment by kipk49** [comment]
[BigErrorMessage.txt](https://github.com/cyclus/cyclus/files/3393063/BigErrorMessage.txt)

:(

**Comment by bam241** [comment]
ok I don't know why you got python 3.7 but try:
```
conda config --add channels conda-forge
conda install cyclus-build-deps python=3.6
```

**Comment by kipk49** [comment]
Success! I have a working installation. Behold and despair:

- Downloaded Linux installer off of Anaconda website at https://www.anaconda.com/distribution/#download-section

- Moved the shell file to Home directory via GUI
- 'bash Anaconda3-2019.03-Linux-x86_64.sh'
- 'echo 'export PATH="~/anaconda/bin:$PATH"' >> ~/.bashrc'
- 'source .bashrc'
- 'conda config --add channels conda-forge'
- 'conda install -y openssh gxx_linux-64 gcc_linux-64 cmake make docker-pycreds git xo python-json-logger python=3.6 glibmm glib=2.56 libxml2 libxmlpp libblas libcblas liblapack pkg-config coincbc=2.9 boost-cpp hdf5 sqlite pcre gettext bzip2 xz setuptools nose pytables pandas jinja2 cython==0.26 websockets pprintpp'

This works; for some reason this version of Cyclus displays the input file in XML format in the terminal while running, but it's close enough for government work.

**Comment by robfairh** [comment]
Good job @kipk49 !! Thanks @bam241 for the help!!

**Comment by bam241** [comment]
I think in some way we need to document this... to fix it in the future...

**Comment by gwenchee** [comment]
I just used https://github.com/cyclus/cyclus/issues/1524#issuecomment-511476697 to set up cyclus and cycamore using a fresh ubuntu 16.04 and it works! Kudos to @kipk49

**Comment by DanJack1987** [comment]
> ```
> (base) kip@kip-arfc:~$ conda install -y  cyclus-build-deps
> WARNING: The conda.compat module is deprecated and will be removed in a future release.
> Collecting package metadata: done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - cyclus-build-deps
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/linux-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/free/linux-64
>   - https://repo.anaconda.com/pkgs/free/noarch
>   - https://repo.anaconda.com/pkgs/r/linux-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.
> ```

Hi Rob, 

Did you ever successfully install Cyclus. I am stuck in the exact place you are.

**Comment by DanJack1987** [comment]
Getting stuck exactly where others were with the new installation instructions. Is anyone still updating cylcus or have any idea about how to compile and install rather than running install.py

**Comment by bam241** [comment]
@DanJack1987 have you try to solution provided above ?

**Comment by DanJack1987** [comment]
@bam241 Yeah I did, I will try again on a different computer set up. But for my main desktop in a virtual box behind a company firewall this didn't work. All other attempts I have made have also failed at various points.

**Comment by bam241** [comment]
what is the error you are getting exactly ?
recause the python 37 related error should have been solved with forcing python 36.
I also heard about a issue with numpy and py36... this might be more complicated....

**Comment by DanJack1987** [comment]
So when I try the steps listed in KipK's comment I get a failure during the conda install -y. I am going through the packages 1x1 to determine where it is.

**Comment by DanJack1987** [comment]
Hi I am getting a process killed, I will run with -vv later and can post that if needed.

BTW thank you for helping with this.

**Comment by DanJack1987** [comment]
Hi I completed the install by making a fresh Ubuntu, and using python3 install.py

I had to over come 2 bugs during it and these 3 steps did that. I highly recommend that anyone else with issues do it without conda on a fresh restart and add these steps to the dependencies.
1. install python-is-python3
2. to install python3-pip
3. pip install setuptools

**Comment by DanJack1987** [comment]
@nuclearkatie whenever I tried that it update-alternatives kept being upset that I only had Python3 installed. It might have been something I was doing wrong in that area, but from what I can tell it seems like if you only have python3 on the computer it doesn't want to update the alternatives.
