### ISSUE TITLE
RHEL unable to install due to libxml++-2.6

### ISSUE THREAD

**Issue by DanJack1987** [cyclus/cyclus#1573]
RHEL does not have libxml++-2.6 available is there anyway to install cyclus with libxml++-2.4?

Must run RHEL on labs system for security requirements.

**Comment by nuclearkatie** [comment]
Did you ever try using `libxml++-2.4` or was this just a pre-emptive question because the default installs 2.6? I don't work on Red Hat but our [Dependencies Page](https://github.com/cyclus/cyclus/blob/master/DEPENDENCIES.rst) just says the minimum `libxml++` version is 2.36 so _in _principle__ it could work

**Comment by gonuke** [comment]
Do we have a way to test on RHEL with docker? (@bennibbelink)

**Comment by bennibbelink** [comment]
Potentially, according to this 2020 [article](https://developers.redhat.com/blog/2020/03/24/red-hat-universal-base-images-for-docker-users#). The [redhat/ubi8](https://hub.docker.com/r/redhat/ubi8) image looks to be kept up to date.  I can experiment building cyclus on this image and see how involved it is / how much it diverges from an ubuntu build.

**Comment by bennibbelink** [comment]
I found `rockylinux` as an open-source alternative to `redhat/ubi` that should be "bug for bug compatible".  The Dockerfile below builds and passes unit tests but fails one of the python tests (`test_include_recipe.py` - Relax-NG validity error : Extra element recipe in interleave.). I'm still trying to work out what's going wrong but I figured I would put this up here for any feedback in the meantime. 

The version of `libxml++` installed  by `yum` is 2.42.

```dockerfile
FROM rockylinux:9 as common-base

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN yum update -y

FROM common-base as yum-deps
RUN alternatives --install /usr/bin/python python /bin/python3 10
RUN yum install -y 'dnf-command(config-manager)' &&  yum config-manager --set-enabled crb && yum install -y epel-release

RUN yum install -y \
        wget \
        which \
        git \
        gcc \
        gcc-c++ \
        make \
        cmake \
        hdf5-devel \
        libxml2-devel \
        libxml++-devel \
        boost-devel \
        liblas-devel \
        lapack-devel \
        sqlite-devel \
        pcre2-devel \
        gettext \
        xz \
        python3-devel \
        python3-setuptools \
        python3-pip \
        python3-pytest \
        python3-jinja2 \
        python3-tables \
    && yum clean all

RUN mkdir -p $(python -m site --user-site) && python -m pip install pandas cython

FROM yum-deps as cyclus
ARG make_cores=2

COPY . /cyclus
WORKDIR /cyclus

# Uncomment the following line to run cmake in verbose mode.
# This is sometimes useful for debugging.
#ENV VERBOSE=1

# You may add the option "--cmake-debug" to the following command
# for further CMake debugging.
RUN python install.py -j ${make_cores} --build-type=Release --core-version 999999.999999
ENV PATH /root/.local/bin:$PATH
ENV LD_LIBRARY_PATH /root/.local/lib:/root/.local/lib/cyclus

FROM cyclus as cyclus-test

RUN cyclus_unit_tests

FROM cyclus-test as cyclus-pytest

RUN cd tests && python -m pytest

```
