### ISSUE TITLE
I failed to install cyclus successfully.Please help me.

### ISSUE THREAD

**Issue by WHYAOAOAO** [cyclus/cyclus#1574]
I used the virtual machine to install cyclus. When I input "$CONDA install - C CONDA forge cycamore, $CONDA config -- set ssl_verify false, $CONDA install - C CONDA forge cycamore" on the Ubuntu terminal, the installation failed.Then I tried some other methods, and each of them failed
![微信图片_20220310141951](https://user-images.githubusercontent.com/101578897/158203268-e8445957-cca7-4a4f-adfd-176caa3dcc9e.png)
![微信图片_20220310141958](https://user-images.githubusercontent.com/101578897/158203273-b2911004-02a7-4dea-8d83-0690eba82594.png)
![微信图片_20220310142006](https://user-images.githubusercontent.com/101578897/158203276-42b318b0-cf4d-4990-bb35-3e471ad74102.png)
.

**Comment by DanJack1987** [comment]
Following. Similar problem. However I get stuck at [57%] linking CXX executable ..bin/cyclus/unit test while installing. I am trying to find ways past this but I have all the dependencies installed and still get stuck here every time I try it.

**Comment by nuclearkatie** [comment]
@WHYAOAOAO were you able to install Cyclus? If so, could you comment the way you resolved your previous issue and then close the issue? Thansk!

**Comment by WHYAOAOAO** [comment]
I have installed Cyclus.I I reinstalled the whole virtual machine, and then the problem was solved inexplicably

**Comment by nuclearkatie** [comment]
Glad you got it working! Sounds like the software equivalent of "turning it off and back on again" 😂

I'm going to close the issue now, feel free to reopen it or open a new one if other issues arise
