### ISSUE TITLE
Cyclus install fail on Ubunutu VM in windows

### ISSUE THREAD

**Issue by DanJack1987** [cyclus/cyclus#1585]
CMake Error at cmake/UseCyclus.cmake:136 (message):
  cycpp failed on '/home/daniel/cyclus/tests/test_agents/test_agent.cc' with
  exit code '1'
Call Stack (most recent call first):
  cmake/UseCyclus.cmake:245 (USE_CYCLUS)
  tests/test_agents/CMakeLists.txt:3 (install_cyclus_standalone)

**Comment by DanJack1987** [comment]
[CMakeError.log](https://github.com/cyclus/cyclus/files/12089996/CMakeError.log)
[CMakeOutput.log](https://github.com/cyclus/cyclus/files/12089997/CMakeOutput.log)

**Comment by gonuke** [comment]
Thanks for the feedback @DanJack1987 .  We are working to resolve and modernize the build issues in #1588 and will check back with you when it's ready.

**Comment by gonuke** [comment]
Per discussion in #1700, we will no longer povide VM images since we provide a number of other avenues for installation
