### ISSUE TITLE
Build Issues in Aug 2023. Am also wondering, is there any interest to rewrite in Rust?

### ISSUE THREAD

**Issue by theodoreOnzGit** [cyclus/cyclus#1586]
Hi.

I've been having build issues with Cyclus, and I see many have similar issues. It was done on WSL2 ubuntu, essentially a VM.

I've tried dependencies from the apt repositories then building cyclus from source, it doesn't work. 
I've tried installing dependencies from conda, and then building according to the installation instructions, doesn't work.
I've tried installing cyclus and cycamore directly from conda and it doesn't work either.

Each has a different error, usually to do with dependencies. I see we have some sort of dependency hell going on here unfortunately.

I'd like to ask though, if one wants to avoid the problem of cmake, make and mitigate some issues with dependency hell,
Would anyone be interested in a rewrite of Cyclus in Rust? Hopefully in a way that minimises the dependency hell issue.
(and I mean only Rust, no python, such an interface should be a separate repo)

I may be interested to try this out as a fun side research project. 
Of course, I would need to see how the unit tests work, but I currently
can't even compile Cyclus, let alone run the tests.

I've had a great experience working with cargo and it makes compilation generally a breeze compared to figuring out make and cmake, 
plus dependencies do compile faster if one compares it to conda, 
and the dependency download process doesn't hang like it does on conda,
and you don't have to go down the rabbit hole of doing mamba or other stuff.

**Comment by abachma2** [comment]
Hi @theodoreOnzGit. Thank you for bringing up this issue. We recognize that the the build process for Cyclus is very involved. WE currently have a PR being reviewed (#1588) that aims to update some of the dependencies of Cyclus to make it easier to build it.

**Comment by abachma2** [comment]
Hi @theodoreOnzGit! We have done some maintenance work on the Cyclus build to hopefully make it easier to install the dependencies and build. If you have some time, would you please pull the latest updates and install cyclus? We would really appreciate your feedback on if you are still having these build issues before we publish a new release.

**Comment by gonuke** [comment]
Since we have addressed the dependency issues for now with updated dependencies and fewer pinned old versions, and we don't have the bandwidth of funding for a rewrite in rust, we will close this for now.  We welcome additional feedback if you have any @theodoreOnzGit

**Comment by theodoreOnzGit** [comment]
Sorry for late reply. I pulled cyclus off and built it using anaconda environment. Seems to work! 

Acknowledged that there's probably no bandwidth  or funding for a Rust rewrite. Totally understand. 

Thank you for your thoughtful replies though. Have a good one
