### ISSUE TITLE
introduce code coverage measurement to CI

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus#1591]
It will be valuable to have some measure of how much of our code we are covering in CI.  Through work on #1588 I got the impression that there are core methods implemented in C++ that are tested only in the python testing. I'm not sure that's a good state to be in.  It would be useful to know how much coverage we get from gtest alone vs gtest + pytest.

**Comment by bennibbelink** [comment]
If you take a look at the `main` branch of my [fork](https://github.com/bennibbelink/cyclus), I have modified the `build_test.yml` workflow to use `lcov` and coveralls to report code coverage (and add a badge in the README).  This [PR](https://github.com/bennibbelink/cyclus/pull/6) shows what kind of PR features we get from coveralls, including a total coverage threshold for failure and a coverage decrease threshold for failure.  These thresholds (as well as some other settings) are controlled in the repo settings in [coveralls](https://coveralls.io/github/bennibbelink/cyclus).

Let me know what you think @gonuke , and I can implement this for `cyclus/cyclus`

**Comment by gonuke** [comment]
This looks great!! Looking forward to seeing it in the main repo

**Comment by bennibbelink** [comment]
In order to get comments on PRs someone with appropriate privileges will need to follow these [instructions](https://docs.coveralls.io/app-notifications).  It may take some playing around with to see what is necessary.  Hopefully it is as simple as adding the [Coveralls GitHub app](https://github.com/marketplace/coveralls/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4zMDA=#plan-300) to the cyclus organizational account, but I'm not sure

Also, if you log into coveralls with your github account you should be able to see all the settings associated with `cyclus/cyclus` and modify them as you wish

**Comment by gonuke** [comment]
I think I have completed those steps (waiting for Coveralls to accept the invite).  Do you have a good way to test/confirm, @bennibbelink ?

**Comment by bennibbelink** [comment]
I tried re-running the workflows to trigger a comment from coveralls on the PR.  I can try making another PR now that Coveralls has privileges to see if the comment is generated, but I thought it should be generated now.  

Other than that aspect, we can see the results from this PR [here](https://coveralls.io/github/cyclus/cyclus), and we can see a badge on the README in my branch.  One thing that might need to change, should the badge represent the coverage on the current branch, or always just the coverage on `main`? Currently it is hardcoded to `main`

**Comment by gonuke** [comment]
Maybe if you convert #1616 to a regular PR instead of a draft, it will trigger things?

**Comment by bennibbelink** [comment]
I wonder if now that it is merged to main we will see the comments.  The comments show the difference in coverage between the PR and `main`, so maybe it just didn't have a baseline report(?).  Guess we'll find out soon as PRs get opened
