### ISSUE TITLE
Remove Docker image dependency from CI tests

### ISSUE THREAD

**Issue by abachma2** [cyclus/cyclus#1595]
Currently, Docker image pushing is only available from upstream branches (i.e., from cyclus/cyclus.git). Docker image pushing is required for the CI tests, so allowing Docker image pushing from any forked branch is desired so that CI can properly test for changes on PRs from a a fork. 

This issue can be closed when the Docker image can be pushed from a forked branch.

**Comment by gonuke** [comment]
This is, unfortunately, not quite the solution- GitHub fundamentally prevents this as a security measure.  The real fix is for CI tests to not rely on pushing docker images.

**Comment by abachma2** [comment]
Renamed the issue. So this issue can now be closed when CI tests for building and testing can be run in PRs from forked branches (which was always the ultimate goal, just adjusting how that is accomplished).

**Comment by gonuke** [comment]
I think the strategy employed in svalinn/DAGMC is the best strategy here and @bennibbelink discussed today.  Hopefully it can be implemented fairly quickly.
