### ISSUE TITLE
Allow trades to be a vector

### ISSUE THREAD

**Issue by nuclearkatie** [cyclus/cyclus#1681]
Right now, trades have to be a single resource (material or product). In order to implement packaging, trades need to be allowed to be vectors (and potentially vectors of vectors for transport units...)

Or maybe, offers to requests need to be allowed to be vectors. Then, trades can still be single resource, but the DRE would have to be able to compare multi-pronged offers to regular, single resource offers, and multiple trades could result from a single request
(now that I'm writing it out, the second one seems more complicated)

**Comment by gonuke** [comment]
(capturing some in-person discussion) - This specifically necessary in the step of executing a trade when the trade negotiation in the DRE may not have been for a specific number of packages, but the trade will be executed as a specific number of packages.  Thankfully, it should not have any bearing on the mathematical definition of the problem being solved by the DRE.

**Comment by nuclearkatie** [comment]
The need for trades to become vectors of materials/products has been avoided for now, with the current implementation of packaging in the MatlSellPolicy (#1749). In that case, the prospective seller makes multiple bids, which sum up to the total request it can satisfy. Each bid corresponds to material that can be packaged in a single package. Then, each successful trade corresponds to a single package of material.

Also, #1749 allowed the package to be submitted along with the bid. While nothing is currently done with this information, in principle a requester could use that information to check before accepting a trade (especially for less than the orginal bidded amount) is still packagable. Otherwise, if accepting less than the bid for material that will be packaged, the trade could fail to execute as noted in #1752
