### ISSUE TITLE
Issue release

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus#1685]
With the new robustness in the build process and a few new features, we should issue a new formal release.  This will take carefully oversight from @gonuke and @bennibbelink

**Comment by ahnaf-tahmid-chowdhury** [comment]
Can you please describe the issue a little bit more? Or, maybe created mistakenly?

**Comment by gonuke** [comment]
Definitely want new releases of all three projects together

**Comment by bennibbelink** [comment]
I believe we are ready for release on the version management front.  PRs are merged in cyclus (#1696) and cycamore ([#589](https://github.com/cyclus/cycamore/pull/589)). I don't think cymetric needs any modification - its version string exists in a single place (`setup.py`). 

Are there any other blocking issues?

**Comment by abachma2** [comment]
I think we should make sure we take care of #1703 and #1706 (either merging or closing) before issuing a release. I think both of those cover important things to clean up before a new release.

**Comment by bennibbelink** [comment]
Release 1.6.0 has been issued for [Cyclus](https://github.com/cyclus/cyclus/releases/tag/1.6.0), [Cycamore](https://github.com/cyclus/cycamore/releases/tag/1.6.0), and [Cymetric](https://github.com/cyclus/cymetric/releases/tag/1.6.0), closing this issue.
