### ISSUE TITLE
Clean up GHCR

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus#1705]
We should remove a lot of outdated packages pushed to GHCR - I think we really only need to keep:
- <base image_pkg_mgr>/cyclus
- <base image_pkg_mgr>/cycamore
- <base image_pkg_mgr>/cymetric

**Comment by bennibbelink** [comment]
### A more well-defined state of the Cyclus GHCR

Given the state of our current CI strategy we should maintain the following packages in our registry:
#### Cyclus Packages
- `cyclus_20.04_apt/cyclus`
- `cyclus_20.04_conda/cyclus`
- `cyclus_22.04_apt/cyclus`
- `cyclus_22.04_conda/cyclus`
- `cyclus_rocky_8/cyclus`
- `cyclus_rocky_9/cyclus`
- `cyclus_20.04_apt/cyclus-coverage`
- `cyclus_20.04_conda/cyclus-coverage`
- `cyclus_22.04_apt/cyclus-coverage`
- `cyclus_22.04_conda/cyclus-coverage`

#### Cycamore Packages
- `cycamore_20.04_apt/cycamore`
- `cycamore_20.04_conda/cycamore`
- `cycamore_22.04_apt/cycamore`
- `cycamore_22.04_conda/cycamore`

#### Cymetric Images
- `cymetric_20.04_apt/cymetric`
- `cymetric_20.04_conda/cymetric`
- `cymetric_22.04_apt/cymetric`
- `cymetric_22.04_conda/cymetric`

@gonuke I do not have permission to access the package settings to delete the rest of the packages in our registry.  The majority of them are products of older CI strategies, except for the [`cyclus`](https://github.com/cyclus/cyclus/pkgs/container/cyclus) package from 2021.

**Comment by gonuke** [comment]
@bennibbelink - I think I just put you in a team that has admin rights to the 4 main repos

**Comment by bennibbelink** [comment]
Thanks @gonuke! The package registry is cleaned up.  I'll let you review GHCR to confirm and close the issue.

**Comment by gonuke** [comment]
Looks good - thanks!
