### ISSUE TITLE
New Dependency Table Column

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus#1710]
In the table of dependencies it might be helpful to add a new column to identify which options require which dependencies.

**Comment by abachma2** [comment]
Do you need any help on this one @bennibbelink ?

**Comment by bennibbelink** [comment]
Sure! I just hadn't gotten around to this yet but you're more than welcome to take over this issue

**Comment by bennibbelink** [comment]
Correct.  In the standard dependencies table I think the `coin-or` libraries are the only "options", what are your thoughts about combining it with the "optional dependency" table below it?

**Comment by abachma2** [comment]
We definitely should revisit what's listed as required vs optional, as we've discussed in the slack. I think we should keep the dependency tables separate. We may also want to revisit the `conda install` command in the `README` if some of those dependencies are truly optional. It's a lot of packages and as we saw in doing some of the updates for v1.6, it's non trivial to make sure our documentation has correct versions for all of them
