### ISSUE TITLE
Fix links in INSTALL.rst

### ISSUE THREAD

**Issue by abachma2** [cyclus/cyclus#1713]
PR #1703 got merged before I could point out that we are missing some underscores to link to other files in `INSTALL.rst`, so the links just show up as code instead of as hyperlinks.

**Comment by gonuke** [comment]
oops! sorry

**Comment by gonuke** [comment]
However that may be related to Sphinx formatting vs GH formatting?  There was some thrashing on this in the commit history of #1703

**Comment by abachma2** [comment]
I don't think so. The `README.rst` has underscores after the URLs, (like ``text <URL>`_`) that allows things to render, and the website works with that too.

**Comment by gonuke** [comment]
OK - we'll have to come up with a single approach and make sure it's applied throughout.
