### ISSUE TITLE
Choose a currency/currency surrogate to work with in DRE cost calculations

### ISSUE THREAD

**Issue by dean-krueger** [cyclus/cyclus#1722]
DRE cost calculations will need some form of currency, or surrogate for the same. USD is the obvious one, but using non-specific "currency units" may also make sense, and potentially simplify things. Either way, there should be a single choice of currency to avoid complicated exchange rate considerations.

**Comment by dean-krueger** [comment]
This likely makes the most sense to do in some generic "cost unit" which can then be transformed into a real cost in post processing.

**Comment by gonuke** [comment]
I think we can start with USD since most data we may have for testing/demonstration will be USD based

**Comment by dean-krueger** [comment]
After thinking about this, I agree, and in a larger sense I think this matters less than I originally thought it did. USD it is!
