### ISSUE TITLE
Unpackaged id gets created as id 2, id 1 is not actually tied to a package

### ISSUE THREAD

**Issue by nuclearkatie** [cyclus/cyclus#1730]
We set unpackaged id as equal to 1, but the unpackaged (default) package actually gets created in the xml file loader. Because the package `next_id` is 2 (in package.cc), this means when a simulation is spinning up, the default package type is created with id 2, and resources are automatically given the unpackaged id of 1. Because there is no actual `Package` with id 1, if you try to repackage a resource to unpackaged, an error is raised

**Comment by gonuke** [comment]
I guess this also needs a new test for setting up packages via XML.  All my tests are more local than that.

So, I think the simple thing should be to set `next_id_ = Package::unpacked_id_` when it is initialized in `package.cc`.  Do we also want to change the name of the default to `"unpackaged"` while we're at it?
