### ISSUE TITLE
State of doxygen docs

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus#1732]
I am uncertain as to the state of the `doc/` directory.  I built the docs locally and it appears to produce what is currently at http://fuelcycle.org/cyclus/api/.  According to the [style_guide ](https://github.com/cyclus/cyclus.github.com/blob/source/source/kernel/style_guide.rst) this page is updated nightly, which I am skeptical of :smile:.  

What is the purpose of these doxygen docs - should they be rid of entirely or do we still have a need for them (in which case they need an overhaul)? 

These questions arose from the existence of `doxygen` as a dependency when working on #1710.

**Comment by gonuke** [comment]
I think it is good to have the API docs produced.  

* What kind of overhaul do you think they need? It's not clear from your comments above.
* I've seen updated Doxygen templates that produce more nicely formatted API docs

**Comment by bennibbelink** [comment]
I apologize I made this issue without fully exploring the API docs.  I never realized that we had this thorough of API documentation, it looks like it could be really helpful.  

- The "Main Page" and the "Related Pages" are pretty bare, can we make it more user friendly from that standpoint and point users in the right direction when they land on the page?
- How is this site updated? I haven't been able to find anything in `cyclus/cyclus` or `cyclus/cyclus.github.com` that points to publishing these docs.  I am aware that it is a target in the `Makefile` if you build with `doxygen` in your environment.

**Comment by gonuke** [comment]
I think it gets built as part of cyclus and deployed to that repo's `gh-pages` branch that is then published as: cyclus.github.io/cyclus which should also resolve as fuel cycle.org/cyclus

**Comment by bennibbelink** [comment]
Can confirm that these api docs are out of date - http://fuelcycle.org/cyclus/api/cyc__limits_8h.html.  Working on rebuilding them as part of the site publishing process.
