### ISSUE TITLE
Cleanup compiler warnings

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus#1742]
A few compiler warnings to be tidied up with code changes:

* [ ] src/infile_tree.cc#L79 - if and only if `element` is NULL, we try to call a member function on `element` - guaranteed to fail/segfault
* [ ] src/context.h#L205 - compiler claims NULL but I think the compiler is wrong; can we still do something to fix this warning?

**Comment by bennibbelink** [comment]
Closed by #1811
