### ISSUE TITLE
`cyclus_large` constant

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus#1746]
Many places throughout the codebase `1e299` is used to represent "a very large number".  This is not best practice and I suspect it could lead to overflow errors

**Comment by bennibbelink** [comment]
Turns out we already have constants for this in `cyc_limits.h`:
```
/// maximum (+ or -) value for an integer variable
static const int kIntBoundLimit = std::numeric_limits<int>::max();

/// maximum (+ or -) value for a linear variable
static const double kLinBoundLimit = std::numeric_limits<double>::max();
```

**Comment by gonuke** [comment]
I found those recently, too, but they seemed to be named in a way that was intended for some specific purpose.  Perhaps we can revisit their naming so that it is more clear how they can/should be used.

**Comment by bennibbelink** [comment]
They're not used anywhere in cyclus/cyclus or cyclus/cycamore.  Based on their names it sounds like they might be intended for this specific purpose (specifying an upper/lower bound) but I agree that we could use more intuitive names.  What do you think about changing them to something more generic like:
 - `cy_max_int`
 - `cy_min_int`
 - `cy_max_double`
 - `cy_min_double`


Looking at the rest of this file:
- There are also no instances of `kConstraintEps` anywhere else in the code, and I'm unsure of the use case for it vs. `cy_eps`.
- `kModifierLimit` is used only in `commodity_producer.h` (and a test).  It is describe as `maximum value for a function modifier (i.e., a_i for variable x_i)` in a comment, but its not clear to me whether this is how it's being used in CommodityProducer

**Comment by bennibbelink** [comment]
Trying to clean up places in cyclus and cycamore where we use `1e299` and running into overflow issues in the Enrichment class when calculating enrichment parameters.  It appears that by using `std::numeric_limits::max()` instead of `1e299` there are some calculations that push us over the edge.  @gonuke do you know if `1e299` was picked arbitrarily or is it meant to be an intentional upper bound on some parameters?

**Comment by gonuke** [comment]
I don't recall how we chose 1e299.  Any idea how different it is from the IEEE max double?

**Comment by bennibbelink** [comment]
The IEEE max double is the same as `std::numeric_limits<double>::max()` - roughly `1.8e+308`
