### ISSUE TITLE
Attempting to package a large quantity into small packages can throw vector length error

### ISSUE THREAD

**Issue by nuclearkatie** [cyclus/cyclus#1766]
I set up a toy simulation to play with packaging, where I forgot to set a throughput. So, the source traded 1e299 kg to the storage immediately. This allowed a storage agent with packaging to try to package 1e299 kg of material into packages with `fill_min` of 1 and `fill_max` of 2. Obviously, this broke the simulation because storage tried to create a bid vector with 5e298 bids  for 2 units each.

Could be solved by setting a flag in the material sell policy to check that the number of packages that could be created is less than the relevant numeric limit and throwing a more descriptive error if not.

However, should we be even more restrictive here? We *probably* never want to create billions of resources by way of packaging. But, where's the line?

Error
`terminate called after throwing an instance of 'std::length_error'`
`  what():  cannot create std::vector larger than max_size()`

**Comment by nuclearkatie** [comment]
Should probably raise a useful warning at the very least. Maybe if (quantity / fill_mass) > 10^6 ??

Unless someone is trying to track individual fuel pellets (incredibly high fidelity fuel fab model, maybe?), I can't see how you would otherwise end up with an attempt to create more than one million packaged items from a single resource at once except by accident, as I did

**Comment by bennibbelink** [comment]
> Obviously, this broke the simulation because storage tried to create a bid vector with 5e298 bids for 2 units each.

What do you mean by "broke the simulation"?  Did it terminate for some reason?

**Comment by nuclearkatie** [comment]
Yeah, C++ threw a `std::length_error` which terminated the simulation

**Comment by gonuke** [comment]
per discussion:
* add a warning limit that is a public static variable in `Package` and check against it when appropriate and throw a warning
* also check against `max_size()` and throw an error when that limit is exceeded
