### ISSUE TITLE
`exclusive_orders_only` is deprecated

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus#1768]
Both `cyclus_flat.rng.in` and `cyclus.rng.in` have a comment `<!--deprecated. @TODO remove in release 1.5 -->` for the element `exclusive_orders_only` within `solver`.  It looks like the schema on the website already has this removed, should be a quick fix to remove it from the actual schemas.  @gonuke can you confirm that this is deprecated and should be removed?

**Comment by gonuke** [comment]
@nuclearkatie this seems like something you might have some perspective on, too

**Comment by bennibbelink** [comment]
@nuclearkatie thoughts?

**Comment by nuclearkatie** [comment]
I've never played with this solver option, in fact I only recognize it from its (previous version?) as [`allow_exclusive_orders`](https://fuelcycle.org/user/input_specs/control.html) as listed on the website. I've never had a need to block exclusive orders, which is what this seems to do, so I won't be losing anything I've done if this does in fact get deprecated
