### ISSUE TITLE
Package R-NG schema requires all elements

### ISSUE THREAD

**Issue by nuclearkatie** [cyclus/cyclus#1777]
Need to fix R-NG schema for packaging (and presumably transport units). `fill_min`, `fill_max`, and `strategy` should be optional. `strategy` especially should be optional in the case that `fill_min` and `fill_max` are equal

**Comment by gonuke** [comment]
Our ability to validate grammar with logic is limited.  We can make these all optional, but we can't make their presence depend on each other.  As long as they have reasonable defaults, we can just make them all optional.
