### ISSUE TITLE
Random fill package? Re-do GetFillMass, again?

### ISSUE THREAD

**Issue by nuclearkatie** [cyclus/cyclus#1812]
As I'm using packaging more, I find myself desiring a random fill strategy, even a relatively simple implementation like a uniform distribution between `fill_min` and `fill_max`.

However, this idea doesn't play nicely with `Package::GetFillMass()`, which assumes a single fill mass and returns that number plus the number of packages that can be created at that fill mass.

For some reason, I had avoided making `GetFillMass` return a vector of fill masses, even in the recent change #1790. Maybe because that felt wasteful when all the strategies would have a single fill mass (with the exception of the very last package, which could be smaller)? Is there any other reason not to switch `GetFillMass` to just returning a vector?

**Comment by gonuke** [comment]
I thought of a vector, too, when you were doing it.... it definitely seems like it makes sense..
