### ISSUE TITLE
Cyclus Dockerfile failing with missing libpcre.so

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus#1820]
In a clean build of the Dockerfile with `apt` the build fails with 
```
32.24 make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpcre.so', needed by 'lib/libcyclus.so'.  Stop.
```

I know that we are installing `libpcre2-dev` but it doesn't appear to generate a `libpcre.so` for linking.  For some reason CI is still building successfully. 

Oddly, I get the same problem when I try to build from scratch inside a one of our shared images, which apparently built successfully???

This can be recreated with;
```
docker build --target cyclus --no-cache --build-arg make_cores=16 -t cyclus_local -f docker/Dockerfile .
```

**Comment by gonuke** [comment]
Notes:

My local build claims to find libpcre.so:
```
10.93 -- Found PCRE Libraries (optional): /usr/lib/x86_64-linux-gnu/libpcre.so
```
and then fails here:
```
15.29 [  1%] Building CXX object src/CMakeFiles/eventhooks.dir/eventhooks.cc.o
16.36 make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpcre.so', needed by 'lib/eventhooks.so'.  Stop.
```

Oddly, CI claims to [NOT find libpcre.so](https://github.com/cyclus/cyclus/actions/runs/11254608991/job/31292398306#step:5:441) but then [does successfully build `eventhooks.so`](https://github.com/cyclus/cyclus/actions/runs/11254608991/job/31292398306#step:5:910)

**Comment by ahnaf-tahmid-chowdhury** [comment]
It generally happens when your CMake targets do not include the file or have a different name when the library is built, and you manually add this file to your list.

Please review your CMake targets, as they might have a different file name, which could be causing the issue.

**Comment by gonuke** [comment]
Maybe I had a stray `build` directory with stale CMake config... but this doesn't seem to still be a problem...  I'm closing it for now
