### ISSUE TITLE
improve readability and indexing of LMatrix class

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#495]
currently there are some legacy readability and indexing issues in the LMatrix class. this is a low-level, cosmetic issue.

an example of readability: line 197, aij +=, rather than aij = aij +...

the indexing looks to be an artifact of the original coder being used to indices starting with 1 rather than 0, so there's an offset provided in a number of methods, e.g. M(1,1) returns M_[0][0].

**Comment by gidden** [comment]
moved to 1.4

**Comment by rwcarlsen** [comment]
Closing - we don't use lmatrix for anything now.
