### ISSUE TITLE
compilation problems on Ubuntu 12.04 32bit

### ISSUE THREAD

**Issue by tkozlowski** [cyclus/cyclus#496]
NOTE: there is analogous note in cyclopts about compilation problems on Ubuntu 12.04 32bit.  It is on the same computer, the problems might be related.

I compiled cyclus on Ubuntu 12.04 32bit.  The compilation seems to complete without errors, 'make install' crates appropriate binaries.  However, there are failed cases for 'make test' and 'CyclusUnitTestDriver', see below.

> make test

=== BEGIN ===
... SNIP ...
        Start 149: XMLQueryEngineTest.top_level_throws
149/149 Test #149: XMLQueryEngineTest.top_level_throws ....................   Passed    0.02 sec

96% tests passed, 6 tests failed out of 149

Total Test time (real) =   4.09 sec

The following tests FAILED:
     19 - CompMapTests.massify (Failed)
     29 - EnrichmentTests.enrichmentcalcs (Failed)
     72 - MaterialTest.Extract_complete (Failed)
     73 - MaterialTest.Extract_diff_comp (Failed)
     74 - MaterialTest.Extract_half (Failed)
    133 - SymbolicFunctionTests.expfunc (Failed)
Errors while running CTest
make: **\* [test] Error 8
=== END ===

> ./CyclusUnitTestDriver

=== BEGIN ===
... SNIP ...
[ RUN      ] XMLQueryEngineTest.low_level_queries
[       OK ] XMLQueryEngineTest.low_level_queries (0 ms)
[----------] 5 tests from XMLQueryEngineTest (3 ms total)

[----------] Global test environment tear-down
[==========] 144 tests from 24 test cases ran. (318 ms total)
[  PASSED  ] 142 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] CompMapTests.massify
[  FAILED  ] EnrichmentTests.enrichmentcalcs

 2 FAILED TESTS
  YOU HAVE 5 DISABLED TESTS
=== END ===

Ubuntu is fully updated, all dependencies were installed directly from the repository:

> uname -a

Linux vm1 3.5.0-32-generic #53~precise1-Ubuntu SMP Wed May 29 20:35:31 UTC 2013 i686 i686 i386 GNU/Linux

> g++ -v

g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

> cmake -version

cmake version 2.8.7

> make -v

GNU Make 3.81

> apt-show-versions coinor-libcbc-dev

coinor-libcbc-dev/precise uptodate 2.5.0-2.3

--Tomasz

**Comment by gidden** [comment]
moved to 1.4

**Comment by gonuke** [comment]
Closing this given the passage of time and work in #1588 for a 10 year newer Ubuntu flavor
