### ISSUE TITLE
add tests for matrix-related classes

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#583]
unfortunately, no such tests exists. the classes in question are:

- [ ] LMatrix
- [ ] UniformTaylor

I'm not sure what level of priority this should take, and perhaps would be a good exercise for a new entrant to the dev team, because:
- matrix operations are well-known linear-programming techniques
- the implementation is already written
- it is purely an exercise in writing tests
- we could dovetail documentation issues into this (i.e., make a separate issue to document these classes using doxygen, which both are currently lacking)
- issue #495 could be tackled at the same time

I'll assign to @scopatz for now and let him unassign or reassign.

**Comment by gidden** [comment]
moved to 1.4

**Comment by rwcarlsen** [comment]
closing in favor of #1134
