### ISSUE TITLE
Create Index in the output database

### ISSUE THREAD

**Issue by katyhuff** [cyclus/cyclus#603]
Suggestion from Yarden ( @yarden-livnat ) :

One of the last steps of database creation should be indexing (CREATE_INDEX ? )
Since it takes some time (how much?), it's likely that we will want a flag that turns off this feature for parametric simulation sets (because creating the index at the end of each simulation is fine, but is probably better to do just once at the end of the parametric series).

We should do this probably by adding a line to the create-table function for the sqlite backend that adds the name of that table to the list of tables to index. 

Then, at the beginning of the close-table function in that sqlite backend, create an index based on that list.

**Comment by gidden** [comment]
@rwcarlsen / @yarden-livnat, can you give an update on this issue?

**Comment by rwcarlsen** [comment]
I think that this is the responsibility of cymetric, cyclist, and other
data analysis tools.  I would vote for moving this issue into cymetric and
closing it here.

**Comment by gidden** [comment]
opening cymetric/#54
