### ISSUE TITLE
non-quantity based Extract functions

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#663]
In order to model separations, we need a function extract functions that aren't based on quantity.

Signatures I can think of off the top of my head are:
```
Material::Ptr Extract(Composition::Ptr c);
Material::Ptr Extract(Composition::Ptr c, double efficiency);

Material::Ptr Extract(Iso i);
Material::Ptr Extract(Iso i, double efficiency);

Material::Ptr Extract(std::vector<Iso> is);
Material::Ptr Extract(std::vector<Iso> is, double efficiency);
Material::Ptr Extract(std::vector<Iso> is, std::vector<double> effs);
```

**Comment by gidden** [comment]
moved to 1.4

**Comment by gidden** [comment]
actually, I'm just going to close this since we have a separations facility now. it can be reopened at a later date if necessary.

**Comment by rwcarlsen** [comment]
Agreed.  We can work in 1.4 perhaps to move the separations facility's
function(s) into the toolkit.
