### ISSUE TITLE
Hdf5BackTest failing on Ubuntu 13.10 (32bit)

### ISSUE THREAD

**Issue by opotowsky** [cyclus/cyclus#674]
With a clean install and build, Hdf5BackTest.ReadWrite fails. 

Test output:

``` bash
[ RUN      ] Hdf5BackTest.ReadWrite
/home/opotowsky/cyclus/cyclus/tests/hdf5_back_tests.cc:69: Failure
Value of: d2
  Actual: 3.2183266391468267e-269
Expected: d
Which is: 2.2000000000000002
[  FAILED  ] Hdf5BackTest.ReadWrite (93 ms)
```

**Comment by gidden** [comment]
@opotowsky , can you give an update on this issue?

**Comment by opotowsky** [comment]
This one is DEFINITELY 32 bit-specific

On Fri, Apr 24, 2015 at 11:34 AM, Matthew Gidden <notifications@github.com>
wrote:

> @opotowsky <https://github.com/opotowsky> , can you give an update on
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/issues/674#issuecomment-95986605>.
>



-- 
Arrielle Opotowsky ~ Engineering Physics ~ University of Wisconsin-Madison
Computational Nuclear Engineering Research Group ~
http://cnerg.engr.wisc.edu
Nuclear Forensics Graduate Research Fellow
National Science Foundation Graduate Research Fellow

**Comment by gidden** [comment]
to 1.4

**Comment by gidden** [comment]
actually, I will close based on our previous discussion

**Comment by gidden** [comment]
reopen if you would like to @opotowsky

**Comment by scopatz** [comment]
If the problem still exist, then the issue shouldn't be closed.  I am not clear which previous discussion you are referring to.

**Comment by opotowsky** [comment]
I thought it was established that 32 bit wouldn't be supported?

On Sat, Apr 25, 2015 at 12:27 PM, Anthony Scopatz <notifications@github.com>
wrote:

> Reopened #674 <https://github.com/cyclus/cyclus/issues/674>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/issues/674#event-290015473>.
>



-- 
Arrielle Opotowsky ~ Engineering Physics ~ University of Wisconsin-Madison
Computational Nuclear Engineering Research Group ~
http://cnerg.engr.wisc.edu
Nuclear Forensics Graduate Research Fellow
National Science Foundation Graduate Research Fellow

**Comment by scopatz** [comment]
I don't recall that. I remember talking about it. Can you point me to some documentation to that effect?

**Comment by opotowsky** [comment]
Ah, this was the conversation I was thinking of:
https://groups.google.com/d/msg/cyclus-dev/eTXUSZLiaq8/-FB4QbAI5DoJ

My memory on the topic was poor - I did not realize there was the intention
to support 32 bit. We can work through the issues on my laptop after the
semester is over (if it survives that long - there is a pending
debilitating hardware failure)


On Sat, Apr 25, 2015 at 12:33 PM, Anthony Scopatz <notifications@github.com>
wrote:

> I don't recall that. I remember talking about it. Can you point me to some
> documentation to that effect?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/issues/674#issuecomment-96241890>.
>



-- 
Arrielle Opotowsky ~ Engineering Physics ~ University of Wisconsin-Madison
Computational Nuclear Engineering Research Group ~
http://cnerg.engr.wisc.edu
Nuclear Forensics Graduate Research Fellow
National Science Foundation Graduate Research Fellow

**Comment by gonuke** [comment]
Closing because I think it is probably OK to leave 32-bit behind now.
