### ISSUE TITLE
Decayer has no unit tests

### ISSUE THREAD

**Issue by scopatz** [cyclus/cyclus#760]
/le sigh...

![359jzz](https://f.cloud.github.com/assets/320553/2327460/192fee5e-a3f0-11e3-9a44-56da23ac0f04.jpg)

**Comment by gidden** [comment]
I assume still no unit tests, @scopatz?

**Comment by scopatz** [comment]
This is not my responsibility.

**Comment by rwcarlsen** [comment]
We do have a simple decay test now that checks we hook into pyne decay
correctly and get a reasonable result.  Since we use pyne decay wholesale,
I think we can call this issue resolved.
